### ISSUE TITLE
Incorrect horn-type count while making potions

### ISSUE THREAD

**Issue by tukaima** [Innoxia/liliths-throne-public#101]
If you prepare to enchant a potion, that potion's number of horn types will be used for all enchantment interfaces that you open, until you close the game. Preparing a potion for a race that only has one horn type will cause a demon or cow potion (these have 5 and 2 horn types respectively) to only display one horn type, and preparing a demon potion will cause all other potions to display 5 horn types regardless of how many horn types are actually tied to that race.

**Comment by Innoxia** [comment]
Fixed for upcoming version 0.1.97.5. Thank you for the report!
