### ISSUE TITLE
Bug when equipping and unequipping clothes

### ISSUE THREAD

**Issue by RandomNecromancer** [Innoxia/liliths-throne-public#1010]
When unequipping equipment or equipping in an already occupied slot, the game erroneously identifies the slot as blocked and does not allow the operation to be completed. (version 0.3)

**Comment by CognitiveMist** [comment]
Do any specific slots or clothing items trigger this for you? Or is it all of them?

**Comment by RandomNecromancer** [comment]
especially those that can be blocked by other slots, such as the slots of underwear
