### ISSUE TITLE
Negative Perk Points

### ISSUE THREAD

**Issue by RandomNecromancer** [Innoxia/liliths-throne-public#1011]
sometimes when you level up, instead of gaining perk points, you end up losing them (perk points become negative). I get two points per level (I do not know if that's what should happen, because it was usually only one) and when this problem happens I lose between 5-9 points (not really sure, i'll check it out). (version 0.3)

**Comment by trailof** [comment]
Mind that it could be 2 separate issues, as the issue with your character perk points is not fixed by resetting them.

**Comment by RandomNecromancer** [comment]
You're right, I'll fix this.

**Comment by DrZed** [comment]
#1020 found the issue
