### ISSUE TITLE
[Issue] Found the problem with PerkPoints EXPLAINED

### ISSUE THREAD

**Issue by DrZed** [Innoxia/liliths-throne-public#1020]
https://github.com/Innoxia/liliths-throne-public/blob/86ec99171058adaac6bb08887ad57d5ec2ce8cbe/src/com/lilithsthrone/game/character/GameCharacter.java#L4734

I found the problem with perk points....
You're calling 
![image](https://user-images.githubusercontent.com/5124544/50675348-88353480-0fbb-11e9-975d-20608adf3c24.png)

so are you drunk?

**Comment by DrZed** [comment]
no I'm drunk

**Comment by DrZed** [comment]
Wait I'm not, just wrong comment.

**Comment by DrZed** [comment]
SOMEBODY (I don't join discord servers) Tell Innoxia on the discord, It's an obvious bug that needs addressed soon-ish.

**Comment by DrZed** [comment]
Also I am not entirely wrong with 9/2 = 1 (it's integer division so the .8~ gets dropped immediately)

**Comment by DrZed** [comment]
`
public int getPerkPoints() {
	return getPerkPointsAtLevel(this.getTrueLevel()) + getAdditionalPerkPoints() - this.getPerkPointsSpent();
}
`
Is where the fun starts say lvl is 9
getAdditionalPerkPoints() will get a answer of 11 (due to the base 2 and 9 lvl ups)
for this example lets use 0 spent points
getPerkPointsAtLevel() will return 10 by the drunk math I have up in the first comment. (which is accurate)
so 21 points
So the issue is with either the adding to base variable, or otherwise

Fun Fact the saveAsXML in character calls getPerkPoints() and saves, so if you lvl to 10 (21 points 0 spent), save -> load, you'll have 31 points, save -> load, 41 points YAY!

**Comment by DrZed** [comment]
Keep in mind this is with 0 playtime in the game, I didn't verify it, it just looks as though it'd scale up. I'll go play now.

**Comment by DrZed** [comment]
![image](https://user-images.githubusercontent.com/5124544/50675708-bb78c300-0fbd-11e9-9d8c-fa5c1933651c.png)
Part 1
https://youtu.be/dCptqWX8VS8
Part 2
https://youtu.be/uS4Su9SrFzA

**Comment by DrZed** [comment]
I was right on all accounts

**Comment by CognitiveMist** [comment]
Isn't 9/2 == 4.5 which becomes 4?

Also, that's not a particularly helpful title...
