### ISSUE TITLE
Can't add fetishes through phone screen

### ISSUE THREAD

**Issue by BDPMP** [Innoxia/liliths-throne-public#1033]
Fetishes can't be added by the phone screen, and desire for fetishes cannot be set on the phone screen. Arcane essences are still removed when you attempt to add fetishes.
(Fetishes and desires are still changed by potions, and the phone screen still displays current fetishes/desires.)

**Comment by CognitiveMist** [comment]
Appears to be fixed by #1034, so this can be closed.

**Comment by AceXP** [comment]
I am going through some old issues. Since this one is resolved, could you close it?

Only Inno and the owner of the issue can close issues, and Inno's time is better spent on development.

Thanks!
