### ISSUE TITLE
Innoxia Gift and Half-Demon Race bug

### ISSUE THREAD

**Issue by master9147** [Innoxia/liliths-throne-public#1045]
Drinking the Innoxoa's Gift item just returns a command_unknown and if the player is trying to be half-demon variant of any race the game dosen't identify as such and is just viewed as a lessor demon.

**Comment by jetharius** [comment]
To add to this, all offspring of a litter from a demon or half-demon seem to always generate as female and always the race of the father if the player conceived, and the mother if the npc conceived, even with missmatched parents.  But when both parents are non-demon, the gender and species seem to generate fine.  I tweaked the maxoffspring values in the race class to enable massive litters to test this.
![Capture](https://user-images.githubusercontent.com/39508549/54070250-dadcd800-421a-11e9-9ef2-13d958728730.PNG)
