### ISSUE TITLE
Tooltip for the initial screen "Resume" button is not always simple English

### ISSUE THREAD

**Issue by arpie-steele** [Innoxia/liliths-throne-public#1065]
This is a cosmetic bug found in 0.3.0.7, and traced to current code on the dev branch.

What: Tooltip is not always simple English
How: Unzip into new dir, start game, hover over disabled resume button
Expect: There is not yet a game to resume
Actual: Previously saved game (by the title '') not found in 'data/saves' folder.

This message comes from line 223 of game/dialogue/utils/OptionsDialogue.java
because Main.getProperties().lastSaveLocation evaluated as an empty string which is not the fault of the file system or the player, but simply a consequence of the new runtime directory not having any record of any previously saved game.

**Comment by arpie-steele** [comment]
Proposal (tested versus 0.3.1 on dev branch).

```diff
diff --git a/src/com/lilithsthrone/game/dialogue/utils/OptionsDialogue.java b/src/com/lilithsthrone/game/dialogue/utils/OptionsDialogue.java
index 009c43a4..6e68c5b2 100644
--- a/src/com/lilithsthrone/game/dialogue/utils/OptionsDialogue.java
+++ b/src/com/lilithsthrone/game/dialogue/utils/OptionsDialogue.java
@@ -219,6 +219,8 @@ public class OptionsDialogue {
                                                                
                                                        }
                                                };
+                                       } else if ( "".equals(Main.getProperties().lastSaveLocation) ) {
+                                               return new Response("Resume", "There is no previously saved game to resume.", null);
                                        } else {
                                                return new Response("Resume", "Previously saved game (by the title '"+Main.getProperties().lastSaveLocation+"') not found in 'data/saves' folder.", null);
                                        }
```

**Comment by arpie-steele** [comment]
With the merge, this looks fixed in builds out of the dev branch.

**Comment by AceXP** [comment]
I am going through some old issues. Since this one is resolved, could you close it?

Only Inno and the owner of the issue can close issues, and Inno's time is better spent on development.

Thanks!

**Comment by arpie-steele** [comment]
Looks like this was merged a year ago.
