### ISSUE TITLE
Item dupe on Equip (name)

### ISSUE THREAD

**Issue by 0dr** [Innoxia/liliths-throne-public#1074]
**Version:**   
0.3.1.01 (blogspot link)  

**Java:**  
1.8.0_201

**Description:** 
Whenever you equip an item directly from your Inventory to someone else, the item is not removed from you upon equip.

**Details:**
I've met a child of mine for the first time and invited it back to my home.  
There I opened the inventory management and equipped and enchanted item to the freshly invited char.
The Item was added to him, but never removed from mine.
Afterwards this was true for **ALL** "equp (name)" actions I could perform to **anyone**, until I restarted the game.  

**Error.log:**
I foolishly removed it because I thought I could easily reproduce the bug.
There were several lines about  something something charackter something preset not found (number)

**Comment by Morat2255** [comment]
This doesn't just apply to equipping others. Equipping custom enchanted items to yourself also causes the bug. It doesn't seem to apply to found magic items though.

**Comment by Innoxia** [comment]
Thank you for the report! This will be fixed in 0.3.1.1.
