### ISSUE TITLE
Suggestion: Increase Elemental's default wing size to Large

### ISSUE THREAD

**Issue by LukaDoc** [Innoxia/liliths-throne-public#1075]
In a previous version it had been increased to average sized so it would allow elementals to fly from the get-go, however soon after the default wing size required for biped flight was changed to Large. So I suggest/request that the default wing size be bumped up to Large for convenience's sake.

**Comment by Innoxia** [comment]
Elemental's starting wing size has been increased to 'large' in the upcoming v0.3.1.1 hotfix. Thank you for the suggestion!
