### ISSUE TITLE
Soft lock on leaving harpy nests

### ISSUE THREAD

**Issue by TheWeirdling** [Innoxia/liliths-throne-public#1076]
Since public Versions 3.0 I have been getting soft lock issues with the program.  They manifest when trying to change locations (entering the mansion or store, etc.).  After downloading version 3.1.01 I discovered my old saves still exhibit these problems.  

I figured those saves were corrupted so I started a new character.  Of note is as soon as I finished the prologue I went to submission and got my character turned into a slime.  I then transformed them to have some angelic parts.  They got impregnated by a succubus cultist and gave birth to a half demon.  All actions seamed to be working fine until I finished the harpy side quest.  The game immediately soft locked after I turned in the quest and left the nests.

Below I have both the error log and my save file.  The game will not allow me to save later (the UI breaks) so the save file is just before usurping Brittany's throne and walking back to the exit.

[Debug Save file.xml.txt](https://github.com/Innoxia/liliths-throne-public/files/2912936/Debug.Save.file.xml.txt)
[error navigational and save UI breaks.log](https://github.com/Innoxia/liliths-throne-public/files/2912937/error.navigational.and.save.UI.breaks.log)

**Comment by Innoxia** [comment]
Thank you for the detailed feedback and attached error log! I've got that bug fixed for the upcoming v0.3.1.1 release, which will be out later tonight.
