### ISSUE TITLE
The check for whether or not you can manage your offspring's inventory is backwards.

### ISSUE THREAD

**Issue by NinAc-of-the-Southern-Tower** [Innoxia/liliths-throne-public#1080]
In version 0.3.1.01 I encountered one of my offspring while passing through an alleyway and, unlike in previous versions, I could manage her inventory right away.  However, once I raised her affection to "worshipping" level the inventory button becomes greyed out and unusable.

**Comment by Innoxia** [comment]
Thank you for the report, I've got this fixed for tomorrow's hotfix (0.3.1.1),
