### ISSUE TITLE
Can't Change 'Pet Name'

### ISSUE THREAD

**Issue by ETYounger** [Innoxia/liliths-throne-public#1083]
Can no longer set a 'Pet Name' through and NPC's Manage option. When setting a 'Pet Name' or 'What Your Slave Calls You' all changes default to the Player's Name. If the slave or tenant is your offspring, they will default to calling you dad/mom/daddy/mommy.

**Comment by Innoxia** [comment]
This will be fixed in 0.3.1.1, thank you for the report!
