### ISSUE TITLE
0.3.1.1 - Futanari Testicles option affects all testicles

### ISSUE THREAD

**Issue by LeechingLecher** [Innoxia/liliths-throne-public#1086]
Futanari Testicles option was OFF. Made a brand new game, and my male human character had internal testicles. 

The Transform option with the debug menu doesn't allow External to be selected. Enchanting a potion to make testicles external gives a blurb as if they became external, but a quick Selfie check shows they're still Internal.

Changing Futanari Testicles option to ON gave me balls.

**Comment by AceXP** [comment]
This one is fixed too I would think. With the option off, males will have external balls, and futunari internal. With the option on, both will have external balls.

**Comment by LeechingLecher** [comment]
Odd. I tried to find all the issues I'd opened last night to close them if resolved, but couldn't see this one.
