### ISSUE TITLE
0.3.1.1 - The Search for Aurthur; Find Alexa - Missing Dialogue

### ISSUE THREAD

**Issue by ilmncsm** [Innoxia/liliths-throne-public#1088]
Upon reaching Alexa's nest and choosing "Meet with Alexa" you get a section of dialogue, and then the only choice you have is to press "Scarlett's woe" which seems to be meant to be a new set of dialogue where you explain Scarlett's situation.  Instead it simply repeats the dialogue from "Meet with Alexa" leaving the same dialogue twice in a row, and presenting you with the options of "No Punishment" or "Take Punishment".  Both "No Punishment" and "Take Punishment" seem to work as intended, and the quest does complete, there's just bit of dialogue that's not correctly appearing.

**Comment by Innoxia** [comment]
Thank you for the report! This will be fixed in the next release.
