### ISSUE TITLE
Grow a beard as a female character

### ISSUE THREAD

**Issue by gamesfreak26** [Innoxia/liliths-throne-public#109]
As the title says, are you able to do this (maybe through enchantments)?  

If not, I can have a look at the code and try and implement it?

**Comment by Innoxia** [comment]
I'll add the option for this as soon as I can! :3

**Comment by gamesfreak26** [comment]
Thank You.  Much appreciated.  :)

**Comment by Innoxia** [comment]
Added as an option (disabled by default).
