### ISSUE TITLE
lilaya's neverending pregnancy

### ISSUE THREAD

**Issue by RandomNecromancer** [Innoxia/liliths-throne-public#1094]
I impregnated lilaya and slept many more times than necessary for the pregnancy to end, but it never goes beyond the last stage of pregnancy. I gave her eleven mother's milk, but that did not help.

I'm stuck and I can not make progress on the missions in the main story. if anyone has any ideas that might help other than start another game, please let me know.

**Comment by RandomNecromancer** [comment]
after looking at the error log the problem became obvious:

Version: 0.3.1.1
Java: 1.8.0_201
Main.game.getNPCById(NOT_SET) returning null in method: PregnancyPossibility.getFather()
Main.game.getNPCById(NOT_SET) returning null in method: getFather()
Main.game.getNPCById(NOT_SET) returning null in method: Litter.getFather()

**Comment by Innoxia** [comment]
Thank you for the report! For now, you could try the following (after making a backup of your your saved game in case anything breaks):
1. Open debug menu by typing "buggy" when not in dialogue.
2. Select option 1: "Open parser"
3. Type this into the large box: `[#lilaya.endPregnancy(true)]`
4. Go and see if Lilaya's pregnancy has ended. If not, try `[#lilaya.endPregnancy(false)]`
5. If she still hasn't ended her pregnancy, then something major must have gone wrong. If you send me your save file, I will attempt to fix it and send it back to you.

**Comment by RandomNecromancer** [comment]
i'll try, thank you!

**Comment by Innoxia** [comment]
This has been fixed in the code for the next release. Thank you for the report!
