### ISSUE TITLE
0.3.1.1 - For bid Self Actions does not forbid self actions

### ISSUE THREAD

**Issue by LeechingLecher** [Innoxia/liliths-throne-public#1100]
Just had an NPC take her own oral and vaginal virginity with her tail, very annoying.

**Comment by nonchip** [comment]
that's been fixed for ages, why do you report a bug that's already noted as fixed in more recent patch notes 0.o

**Comment by LeechingLecher** [comment]
You'll notice that I'm reporting it as a bug for 0.3.1.1, which IS the hotfix. 

I started a new game yesterday, on the latest publicly available version, and an imported slave did this.

**Comment by nonchip** [comment]
oh ok that's weird, it happened for me a lot in 0.3.1 and not at all since the hotfix 0.o

**Comment by LeechingLecher** [comment]
It's not a situation I generally run into (virgin tailed enemies) so I don't know how frequent it is, even in the current 0.3.1.1 public version.

**Comment by Innoxia** [comment]
Thank you for the report - this will be fixed in version I push to github later tonight.
