### ISSUE TITLE
Do Not Dye Stacked Items

### ISSUE THREAD

**Issue by Questiondeca** [Innoxia/liliths-throne-public#1118]
*CUT*

Edit: Sometimes Dying stacked items also destroys all but one item from the stack.

Edit 2: The original issue I posted here isn't a real issue/was mis-identified, it was a gui lockup, another occurred later but I was able to exit the enchant screen and confirm I wasn't loosing items through enchanting, however I can confirm that trying to dye an item that's part of a stack will dye that one item and destroy the rest of the stack.

**Comment by Pimvgd** [comment]
Fixed in commit 994d98c2f80f24da14819d496cce7117e4803764

**Comment by Questiondeca** [comment]
Confirmed!
