### ISSUE TITLE
Non-Restricting Restrictions

### ISSUE THREAD

**Issue by Questiondeca** [Innoxia/liliths-throne-public#1123]
Example of issue: Tiger Morphs are Disabled (Furry Preferences) from spawning, a Tiger Morph at level 6 has spawned.

Ver. 0.3.2.2

**Comment by Questiondeca** [comment]
![Lilithsthroneerror](https://user-images.githubusercontent.com/11068959/57502001-fa3dc300-72a6-11e9-853d-f941df96d05f.jpg)


Error persists in Version 0.3.2.3 as of time of posting.

**Comment by Stadler76** [comment]
I couldn't manage to reproduce it. Maybe some other setting?
Could you provide some 'steps to reproduce'? Ideally with a new game.

**Comment by Questiondeca** [comment]
I'll attempt with 0.3.2.6 now, will post after attempt if I can repeat, but in short the steps to reproduce is explore back alleys (Start game selecting "struggle" then manually setting individual male and female settings for each race/subset, as an example all cat subtypes are set to disabled but plain cats to full).

In attempting a new game in 0.3.2.6 with the above settings, the second mugger to spawn was a male tigermorph, despite tigermorphs (both genders) being disabled.

Starting again and choosing Furries! No! does seem to properly disable all furry spawns, manually setting spawns of specific furry types to be allowed from this also appears to restrict properly.

Starting again and choosing Furries! Yes! then manually restricting so that only a couple (used male dog and female cow) furry morphs can spawn also appeared to work properly.

This suggests that it's only an issue with struggle or there's something wrong with settings that carry over from a prior version (which selecting Struggle does not change).

In fact I think this might be the problem now, **Struggle defaulting to last used morph spawn settings**, as the initial new game start with the selection of Struggle was after playing the save with the issue, suggesting there's an error or corruption with the settings of just that save which selecting Struggle carried over.

With that in mind, my suggestion for a fix is to give the Struggle option a default morph spawn setting instead of carrying over the last used to avoid such a corruption from being carried over as well.

**Comment by Questiondeca** [comment]
Reloading the save from the prior version (quicksave would not load after starting a new game, deleted, loaded auto save) the furry preferences remained the same as the last new game, not the same as the settings were when originally loading/playing that save, baring issues with saves I assumed corruption and deleted them.

**Comment by Stadler76** [comment]
AFAICS `[Furries?! Yes!]` sets all furry preferences to **Maximum**, `[Furries?! No!]` sets all furry preferences to **Disabled** while `[Struggle]` leaves the settings unchanged, so I don't believe, that `[Struggle]` is the culprit.

**Comment by Questiondeca** [comment]
Well, at this point I'm convinced it was corrupted settings from a prior playthrough. The blanket changes to preferences by Furries yes and Furries no seem to of cleared the corrupted settings, I'll repost the issue if it appears again but I'm closing this at this point.
