### ISSUE TITLE
Demons in the Streets

### ISSUE THREAD

**Issue by AnonDragonWolfess** [Innoxia/liliths-throne-public#1133]
"The only people able to withstand the storm's thunderous power are demons, and every now and then you see one strutting down the street.​ They sometimes cast a curious glance your way, but most are content to simply ignore you.​"

This plays even after you've been transformed into a demon. It would make more sense if they were no longer be curious when you're in your demon form, and become curious again if you were to take on the appearance of a human again.

**Comment by DL-Vadric** [comment]
Pull request #1141 created as a proposed edit for this issue.

**Comment by Innoxia** [comment]
Fixed in #1141
