### ISSUE TITLE
Extra Actions in sex

### ISSUE THREAD

**Issue by Pugiron** [Innoxia/liliths-throne-public#114]
While having sex with a reindeer girl overseer, each time I select ANY sex action, it ALSO gives me a post saying I am violently ramming my fingers into her ass and she ONLY responds to the hard anal fingering.  This starts as soon as I remove her panties.  I have reloaded the game twice, careful to select ANY sex option that does NOT involve anal fingering, but she only responds as if I am violently raping her ass without lubrication.

**Comment by Innoxia** [comment]
I am unable to replicate this. I think I may have fixed it in a previous version (when I fixed some bugs in the 'ongoing' actions text). I'll close this as "fixed". ^^
