### ISSUE TITLE
anal actions causing loss of lust

### ISSUE THREAD

**Issue by RandomNecromancer** [Innoxia/liliths-throne-public#1143]
after a few cases where npcs lost all their lust during sex, I did some testing and apparently performing anal actions seems to be making npcs lose lust, even in those who do not hate it. (0.3.2.2)

**Comment by Death-Rowe** [comment]
I can confirm that this has been happening in my game as well. Possibly related to this is an issue when having sex with Lilaya, in which a female PC can have Lilaya drop to 0 Lust and end sex with a -200 affection hit. I would make a separate issue for this, but I think it could be related to this one.

**Comment by RandomNecromancer** [comment]
I had the same problem and from what I remember it was because of this bug

**Comment by AnonDragonWolfess** [comment]
I have noticed this with Lilaya. Her lust gradually dropped while she was Tail-Pegging my female character, even when I set the Sex Pace to Rough.

**Comment by AnonDragonWolfess** [comment]
Can confirm it even happens when self-pleasuring anally when your character has the Butt-Slut fetish.
