### ISSUE TITLE
creampie with strap-on angers lilaya

### ISSUE THREAD

**Issue by RandomNecromancer** [Innoxia/liliths-throne-public#1151]
**Describe the bug**
Lilaya acts as if a strap-on were a real penis, asking to pull out and getting angry if the creampie option is chosen.

**Expected behavior**
Lilaya should not warn to pull out or get angry if creampie is chosen while the main character is wearing a strap-on

**To Reproduce**
1. Equip a strap-on
2. Start sex with Lilaya
3. Choose Fuck her
4. Choose Creampie upon reaching orgasm

**Attach files**
"Lilaya grins as she sees that you're wearing a strap-on."
"Pull out! I'm not getting pregnant!"
*Creampie*
"Lilaya suddenly realises what you've just done, and as she feels your cum dripping out of her irresistible kitty, she lets out an angry cry and violently shoves you away from her."

Full Dialogue attached.
[Dialogue.txt](https://github.com/Innoxia/liliths-throne-public/files/3161769/Dialogue.txt)

**Additional information:**
 - Game version 0.3.2.3
 - OS: Windows 10
 - Using .jar
 - Java 1.8.0_201

**Comment by A-haron** [comment]
Seems you can even impregnate people with a strap-on under certain conditions.

Investigating, gonna come back.

May require some work on the "penis" definition of the game.

**Comment by RandomNecromancer** [comment]
although lilaya does not get angry, some descriptions, such as initial penetration, continue to treat the dildo as if it were a real penis
