### ISSUE TITLE
Trying sex with a partner while they are on a party

### ISSUE THREAD

**Issue by SephVEVO** [Innoxia/liliths-throne-public#1153]
So, when you have a partner (one that you find on the streets and you get them home) on your party and try to sex them on their room, the game softlocks with your partner and a clone that's (_somehow_) on your party watching you jerk yourself off for eternity until you load or something.

To Reproduce:
1. Have someone that you took out from an alley (The ones that have the "talk" option when defeated) to love you (worship status);
2. Add them to your party;
3. On the same partner, select the option to have normal sex with them (note that the option "Side-by-Side" is available, even though it's only you and your partner that's on the room);
4. Enjoy your fapping session for eternity.

Additional information:
 - Game version: 0.3.2.3 alpha
 - OS: Windows 7
 - EXE Version.

**Comment by A-haron** [comment]
Could reproduce @ 0.3.2.3 alpha prebuild (.exe)

This is what I got from the code:
[OccupantDialogue.OCCUPANT_START.getResponse(0,5)](https://github.com/Innoxia/liliths-throne-public/blob/ab24f7ea537b5b2523255392b520658c2d4175e3/src/com/lilithsthrone/game/dialogue/npcDialogue/OccupantDialogue.java#L219) and [GameCharacter.addCompanion()](https://github.com/Innoxia/liliths-throne-public/blob/ab24f7ea537b5b2523255392b520658c2d4175e3/src/com/lilithsthrone/game/character/GameCharacter.java#L4053) add the occupant as partner, as expected.

But, if you don't return to the room's menu, and use the first button on the second tab (Sex options), [OccupantDialogue.OCCUPANT_START.getResponse(1,1)](https://github.com/Innoxia/liliths-throne-public/blob/ab24f7ea537b5b2523255392b520658c2d4175e3/src/com/lilithsthrone/game/dialogue/npcDialogue/OccupantDialogue.java#L219). Creates a [SMGeneric](https://github.com/Innoxia/liliths-throne-public/blob/ab24f7ea537b5b2523255392b520658c2d4175e3/src/com/lilithsthrone/game/sex/managers/universal/SMGeneric.java#L33) with the occupant as submisive and dominant observer at the same time, which probably produces the error down the line.

Other options end up with the partner as Dominant and Submisive at the same time, or don't work at all (If you try putting "your partner" and "the occupant" as submisive at the same time).

Easiest fix is probabily to "reload the room" after adding an occupant to the party, as the occupant iteraction menu is disabled if the occupant is in your party.

**Comment by A-haron** [comment]
Pull request #1154, propossed fix for this.

**Comment by Innoxia** [comment]
Will be fixed when code is pushed to github later tonight.
