### ISSUE TITLE
An awkward result of templates (Grammer, Minor issue).

### ISSUE THREAD

**Issue by Questiondeca** [Innoxia/liliths-throne-public#1167]
**Describe the bug**
Awkward grammar resulting from the use of a template in descriptions.
Reads: You does not have any crotch-boobs or udders.​

This suggests that the player description for no Crotch-boobs is referencing the NPC template, instead of a player template.
**Expected behavior**
Should read: You do not have any crotch-boobs or udders.​
**To Reproduce**
Use the Selfie option on phone, don't have crotch boobs/udder(s), read the description

**Additional information:**
 - Game version 0.3.3
 - OS: Windows 10
 - Using .jar (Gitbuild)
- Java version: [1.8.0_211]

**Comment by AceXP** [comment]
The selfie option has been changed some time ago, and now when you have no crotch boobs/udders, the whole paragraph is left out. Which also circumvents this issue (but it may have been fixed earlier as well).
Could you please check this and close this issue?

**Comment by Questiondeca** [comment]
Paragraph is not left out but the grammar has been corrected, will still close issue.
