### ISSUE TITLE
Resting prevents saving. (Minor)

### ISSUE THREAD

**Issue by Questiondeca** [Innoxia/liliths-throne-public#1168]
**Describe the bug**
Attempting to save (any type of save) after resting in your room is disabled.

**Expected behavior**
You normally are able to save in your room.

**To Reproduce**
Rest in your room.
Attempt to save.

**Additional information:**
Further behaviour: This only occurs when the "You feel completely refreshed!" green message is on screen, making it a unique scene, where as the normal scene is normal and thus you can save in it.

Refreshing the scene by checking slaves or leaving and re-entering the room re-enables saves in your room.

Version 0.3.3
 - OS: [Windows 10]
 - .jar
- Java: [1.8.0_211]

**Comment by AceXP** [comment]
This has been fixed some time ago, could you check it and close this issue?

**Comment by Questiondeca** [comment]
Yep, As you stated, fixed some time ago, just never closed.
