### ISSUE TITLE
quadruple rooms are not working

### ISSUE THREAD

**Issue by RandomNecromancer** [Innoxia/liliths-throne-public#1178]
**Describe the bug**
When buying the quadruple room the money is spent, but the room remains empty

**Expected behavior**
The empty room should've been replaced by a quadruple room

**To Reproduce**
1. Go to an empty room
2. Click on the quadruple room's buy button with enough money in the inventory

**Attach files**
[error.zip](https://github.com/Innoxia/liliths-throne-public/files/3292798/error.zip)

**Additional information:**
 - Game version: 0.3.3.8
 - OS: Windows 10
 - Using .jar 
 - Java 1.8.0_211

**Comment by DerMaskierte** [comment]
Until this bug is fixed, it is possible to bypass the bug by placing a single room, then upgrading it to quad.
