### ISSUE TITLE
Various bugs in  version 0.3.4.1

### ISSUE THREAD

**Issue by TheWeirdling** [Innoxia/liliths-throne-public#1207]
Sex position bugs:

In the sixty-nine position it is not possible for both characters to perform a blowjob.  It is possible for one character to fellate the other while receiving cunnilingus.  It should be possible for both characters to perform fellatio at the same time.

It is not possible to give a character a hand-job if you are already penetrating them with a penis but you can give them a hand job, then penetrate them and have both actions working at once.  You should be able to give them a hand-job regardless of weather or not they are being penetrated.

Update: It IS possible to give a character a handjob after penetration in the standing position.  Perhaps some actions need better inheritance/modularization to be more uniformly accounted for in each position?

It is possible for a character to receive both cunnilingus and a blowjob from the same character at the same time if you start with cunnilingus.  These actions should be mutually exclusive (maybe characters with really long tongues could do something fun with them though?)

Other bugs:

During an arcane storm it is possible to access the ally way attacker "talk" dialog while you have a character in your party on a non-ally title.  This results in the standard ally dialog and leaves the character in the square but with no ability to interact with them.  This option should not be available.

Typos:

The descriptive words in recovering orifice dialog are swapped.  The descriptions reads recovering to (larger number) from (smaller number).  It should state recovering to (smaller number) from (larger number).

**Comment by AceXP** [comment]
These issues have all been fixed for some time now. Could you please check it and close this issue?

**Comment by TheWeirdling** [comment]
I see, sorry I didn't realize I needed to close the issue.

As of version v0.3.9.1 sixty-nine blowjob initiation is still partially bugged.  If you start using your penis on your partner first (paizuri, blowjob, nipplefucking) you will be unable to give them a blowjob.

**Comment by AceXP** [comment]
I think all sex actions will get an overhaul at one point, but it might take some time.
