### ISSUE TITLE
Throat Transformations

### ISSUE THREAD

**Issue by RandomNecromancer** [Innoxia/liliths-throne-public#1209]
There is no way to transform your throat (wetness, capacity, plasticity and elasticity) after becoming a demon, as there is nothing but a few modifiers in the transformation menu (tentacles, ...). Also, these enchantments cannot be used on items, although it is possible to use similar enchantments on other parts of the body such as pussy and penis (it is possible, however, to transform a non-demon using potions).

I believe you intend to add these options in the future, but as you could end up forgetting or maybe not even realizing they were missing, I decided it wouldn't hurt to write this down

**Comment by Twand37** [comment]
You _can_ still transform your throat as a demon through potions. Any non-racial transformation that you can't access through demonic self-transformation _are_ still possible to adjust through potions.

But yes, I agree that it's strange that these transformations are not possible through the self-transformation menu. Not even slimes can do them, which is even stranger.

**Comment by RandomNecromancer** [comment]
I thought potions didn't work on demons... am I mistaken or do they only work because there aren't any buttons on the transformation menu yet?
