### ISSUE TITLE
3.4.5 dev bug

### ISSUE THREAD

**Issue by Ian-Luminus** [Innoxia/liliths-throne-public#1211]
Buying items doesn't work. The items disappear from NPC inventories, flames are taken from you, but you don't gain the item.

**Comment by luckyshot940** [comment]
the issue is actually the item being sent to the buyback menu for me. try checking there. of course this also means having to pay double for what you tried to purchase.

**Comment by Ian-Luminus** [comment]
Closing since 0.3.4.6 fixed
