### ISSUE TITLE
i reset my perks and i regret it.

### ISSUE THREAD

**Issue by luckyshot940** [Innoxia/liliths-throne-public#1212]
so while i was busy attempting to fine tune my perk tree as you do when your trying to micro manage... the skill tree broke. legit reset everything down to the basic three that never reset in the history of ever for me. and i couldn't even pick perks either.

**Comment by AceXP** [comment]
This has been fixed for some time, could you check it and close this issue?

**Comment by luckyshot940** [comment]
yup. my bad. forgot i sent this ticket in tbh.
