### ISSUE TITLE
Remove .classpath from git tree

### ISSUE THREAD

**Issue by TadUnlikely** [Innoxia/liliths-throne-public#1216]
The Git tree has the .classpath file committed. This causes breakages on other machines, as the classpath information will not always be the same. Best practice says to remove the .classpath file from the git tree and add it to .gitignore, and let the end user set up their own class path info. In order to merge the tree, I have to revert my classpath changes, then do my git pull, then reapply the changes in order to build the game. See the following StackOverflow question for more: [https://stackoverflow.com/questions/18955149/ignore-classpath-and-project-from-git](https://stackoverflow.com/questions/18955149/ignore-classpath-and-project-from-git)

**Comment by AceXP** [comment]
The .classpath file was added to the .gitignore quite some time ago, and also removed from the repo recently. So could you check it and close this issue?

**Comment by TadUnlikely** [comment]
No longer appears to be an issue.
