### ISSUE TITLE
NullPointerException Roundup and other errors (Formerly Nyan Trap)

### ISSUE THREAD

**Issue by Questiondeca** [Innoxia/liliths-throne-public#1229]
**Describe the bug**
Ui does not update properly when entering Nyan's for the first time.

**Expected behavior**
Ui to update properly.

**To Reproduce**
(In New Game)
Go to Nyan's Clothing Emporium (for the first time)
Click Enter
Click the Stockroom button (Bug 1: The tooltips change, and the buttons switch to the different catagories, but they don't Visually change and appear to still be just the Stockroom Button).
Bug 2: After (unknowingly) selecting the feminine clothing selection, leave trade. You will be trapped back at the Nyan introduction with the Stockroom button, with no travel options and no way to leave as the Stockroom button will do nothing.

**Additional information:**
 - Game version 0.3.5.4
 - OS: Windows 10
 - Using .jar 
- java version: 1.8.0_231

**Comment by Questiondeca** [comment]
Further notes, The visual issue (Bug 1) Applies to Arcane Arts, however Bug 2 does not, all other stores in the mall operate normally. Other stores tested also continue to appear to operate normally.

**Comment by Questiondeca** [comment]
Fix some stores (e.g. Clothing Emporium) being broken #1227 appears to be a fix for this issue. Closing once fix is applied.

**Comment by Questiondeca** [comment]
The Fix for the stores does not correct all instances of the UI failing to refresh when changing scenes, and example is: https://github.com/Innoxia/liliths-throne-public/issues/1232. In all cases the buttons do update but the visual component of the UI does not, giving the impression that:

1. Time is not progressing.
2. That you are trapped in a scene.
3. That the buttons have not updated/switched.

Based on the Error.log from 1232, it's another NullPointerException error.

**Comment by Questiondeca** [comment]
Most of the Errors for 0.3.5.4 found in Github so far are appear to all be NullPointerException Errors, 
Errors with Fixes provided by Github reporters: https://github.com/Innoxia/liliths-throne-public/issues/1232
https://github.com/Innoxia/liliths-throne-public/pull/1227
https://github.com/Innoxia/liliths-throne-public/pull/1231
Non-nullpointerexception Error: Slavery Quest not triggering and acting like it's been completed on new character, no error logged.

**Comment by mrlawlz** [comment]
I think that rounding up all the NullPointerExceptions into one issue is only going to make it more difficult to keep track of them as they're found and eventually fixed. A separate issue for each would work better in my opinion.

**Comment by Questiondeca** [comment]
> 
> 
> I think that rounding up all the NullPointerExceptions into one issue is only going to make it more difficult to keep track of them as they're found and eventually fixed. A separate issue for each would work better in my opinion.

This is more to gather links to already posted NullPointerExceptions for the current version, and if someone finds another I do recommend they post them as a separate issue (and if they have a fix, as a pull). So I don't disagree, but I'm not closing or renaming this.

**Comment by Questiondeca** [comment]
Current Dev build appears to correct all issues but the pre-completed Slaver's License quest, Closing issue.
