### ISSUE TITLE
1st of any month causes game to behave weirdly

### ISSUE THREAD

**Issue by triples941** [Innoxia/liliths-throne-public#1232]
**Describe the bug**
When the date gets to 1st of any month some time-related actions stop working: loitering does not pass time, resting actions in "Your Room" become unavailable, information about duration of effects stops showing. When game saved in this state, the game is unable to load that save properly.

**Expected behavior**
All days behave correctly.

**To Reproduce**
Wait until 1st of any month.
Try to get into "Your Room" and open "Actions"

**Attach files**
After trying to open "Actions"
[error.log](https://github.com/Innoxia/liliths-throne-public/files/3826319/error.log)

**Additional information:**
 - Game version: 0.3.5.4
 - OS: Windows 10
 - Running .jar from IDE.

**Comment by triples941** [comment]
I managed to get through the 1st of December by changing in DateAndTime.julianDayToDate line
`int day = (int) (B-D-F+(Q-Z)) + 1;`
to
`int day = (int) (B-D-F+(Q-Z));`
but I am not yet sure if this has any side-effects.

**Comment by Corvall** [comment]
@triples941 Been having this same issue for quite some time now. How exactly do you get to that line in the game's code? And where is it exactly? I have a basic level of understanding of coding, my apologies.

**Comment by triples941** [comment]
@Corvall I started from `RoomPlayer.getMinutesUntilMorningOrEvening` that you can see in the stacktrace of NPE and debugged until I saw that `DateAndTime.julianDayToDate` returns null if it fails to reconstruct `LocalDateTime` due to another exception, and that exception happens to occur because date is too big for a given month, 31 of November in this case.

Probably a better solution would be to detect such cases, reset day to 1 and increment month, but it is not a one-line change, and unfortunately I haven't had enough time to check this.

The exact location for revision 0.3.5.4 is `com.lilithsthrone.utils.time.DateAndTime`, line 197, in the `julianDayToDate` method.

P.S. If the result has been `java.util.Date` and not `java.time.LocalDateTime`, there would be no exception, as `java.util.Date` considers 32 of January equivalent to 1 of February. However, usage of `java.util.Date` is discouraged and a lot of its methods are deprecated, as it has a lot of quirks, many worse than just leniency to the constructor input.
