### ISSUE TITLE
0.3.5.4 - Suckle/Nipple Kiss linked to Nipple Penetration content option

### ISSUE THREAD

**Issue by LeechingLecher** [Innoxia/liliths-throne-public#1239]
Like the title said, the suckle and nipple kissing actions (ongoing as of this version) are enabled/disabled with the Nipple Penetration content option. Suckle should probably be linked to Lactation, and Nipple Kissing should presumably always be enabled.

**Comment by AceXP** [comment]
This has been changed some time ago, and should now be possible with or without that content switched on. Could you check it and close this issue?
