### ISSUE TITLE
Error when submitting to an attacker in the alleyways instead of fighting

### ISSUE THREAD

**Issue by Fortilicious** [Innoxia/liliths-throne-public#1246]
**Describe the bug**
When submitting to a greater cheetah in an alleyway instead of fighting him, I received this message: "Dialogue for 'ALLEY_ATTACK_OFFER_BODY_SOLO_WITH_COMPANION' not found! (Make sure that the 'res' folder is in the same directory as the .​jar or .​exe.​)"

**Expected behavior**
Dialogue from him when submitting to him instead of choosing to fight.

**To Reproduce**
Please include the steps that need to be taken in order to reproduce the bug.
Re-enter the alleyway and initiate the encounter again.  This happens in any alley with any random encounter.

**Attach files**
error log contents:
Version: 0.3.5.8
Java: 1.8.0_231
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...

**Additional information:**
 - Game version 0.3.5.8
 - OS: win 7 pro
 - Using .jar

**Comment by Innoxia** [comment]
Thank you for the report; this issue will be fixed in the next update!
