### ISSUE TITLE
Position of individual gets ignored during sex [2.0.2]

### ISSUE THREAD

**Issue by bicobus** [Innoxia/liliths-throne-public#125]
![javaw_2018-03-03_12-41-06](https://user-images.githubusercontent.com/26164751/36933888-db5c6c9a-1ee0-11e8-9178-b2ee980e89e6.png)
This is a screenshot of scarlet and my character having an anal sexual congress while on all four. For some reason, she manages to still insert her own penis into one of my character's hole.

I simply loaded a save from version 2.0 into version 2.0.2, I don't know if both version are compatible.

**Comment by Innoxia** [comment]
Thank you for the report! This should be fixed for the next version (fixed in #114 ). ^^
