### ISSUE TITLE
Quick sex uses all actions, including gated content

### ISSUE THREAD

**Issue by AceXP** [Innoxia/liliths-throne-public#1256]
[1256.error.log](https://github.com/Innoxia/liliths-throne-public/files/4009789/1256.error.log)

**Describe the bug**
Choosing quick sex uses all actions, even if those activities are normally never used because they are gated behind the content preferences. For example, if nipple penetrations are turned off this can't be used during sex. But it can and will be used in quick sex actions.

Note: this only applies to interactions with unique NPC's, generic ones work as expected.

**Expected behavior**
Gated content should never appear in any activity.

**To Reproduce**
As an example.
Set anal content off in the preferences.
Find a unique NPC to have anal sex with. (For example Rose).
Start sex and choose quick sex.
The description will include sex using her cock and your asshole.

**Additional information:**
 - Game version 0.3.5.8
 - OS: Windows 10
 - Using .jar
-  java version: 1.8.0_221

**Comment by RandomNecromancer** [comment]
quick sex also doesn't give xp if the player has the deflowering fetish and takes a virginity

**Comment by AceXP** [comment]
Fixed in the latest release.
