### ISSUE TITLE
Parser error for Lexi

### ISSUE THREAD

**Issue by cmacleod42a** [Innoxia/liliths-throne-public#1259]
In the harpies nets approaching the matriarch Lexi

> You find yourself standing on the outskirts of Lexi's nest; one of the most populous of all the nests in Dominion.​ Despite the importance of the matriarch who resides here, her nest is no bigger than any of the minor ones scattered throughout the Harpy Nests, and comprises of a single, large platform built into the rooftops of several houses below.​**(Error in conditional parsing!)**

**Comment by Innoxia** [comment]
Thank you for the report! This will be fixed in the next update.
