### ISSUE TITLE
Imps turn into demons after changing femininity out of their gender range 

### ISSUE THREAD

**Issue by Eliria** [Innoxia/liliths-throne-public#1262]
**Describe the bug**
If you change an imp's femininity from their default/preferred gender they will transform into a succubus/incubus, of their original gender, once an update occurs such as moving off and back to their tile.

**To Reproduce**
Change an imp's gender, move off tile and back, they should be a demon. Works whether using a potion or the imp's transformation menu. 

**Additional information:**
 - Ver 0.3.5.8
 - OS: windows 7
 - Using exe
- JRE 1.8_201

**Comment by Innoxia** [comment]
Thank you for the report! This will be fixed in the next update.
