### ISSUE TITLE
The calculation of daytime and nighttime is sometimes wrong

### ISSUE THREAD

**Issue by AceXP** [Innoxia/liliths-throne-public#1266]
**Describe the bug**
The calculation of daytime and nighttime is sometimes wrong. Even though it is the middle of the day, the daytime is shown as night or twilight.

**Expected behavior**
The daytime should be shown correctly.

**To Reproduce**
Please include the steps that need to be taken in order to reproduce the bug.

The problem seems to be that (sometimes) the sunrise/sunset are given for the next day, and this causes the calculation to misfunction.

**Additional information:**
 - Game version 0.3.5.8
 - OS: Windows 10
 - Using .jar 
-  Java version: 1.8.0_221

**Comment by AceXP** [comment]
PR #1263 will fix this issue

**Comment by Innoxia** [comment]
This has been fixed (in a temporary sort of way) in the DateAndTime.getTimeOfSolarElevationChange() method. It should be working properly now.
