### ISSUE TITLE
The NPC in the prologue knows about the MC's penis when this shouldn't be the case

### ISSUE THREAD

**Issue by AceXP** [Innoxia/liliths-throne-public#1272]
**Describe the bug**
In the prologue, Alexandria/Alexander will give you a condom, even if it's not evident that you are male.

**Expected behavior**
Alexandria/Alexander should only offer a condom if you are male, or (when having a feminine appearance) it's obvious you have a penis.

**To Reproduce**
1. Create a new, male androgynous character (default gender description is 'Trap')
2. Have sex with Alexandria/Alexander, (s)he will give you a condom (or two)
3. When your penis is revealed, (s)he will react as if having no idea that you had one.

**Additional information:**
 - Game version 0.3.5.8
 - OS: Windows 10
 - Using .jar
-  Java version: 1.8.0_221

**Comment by AceXP** [comment]
PR #1274 will fix this minor issue.

**Comment by rye1994** [comment]
I feel I need to leave a comment here, women can also carry condoms with them just in case their partner doesn't have one, to be responsible for contraception.

**Comment by AceXP** [comment]
Ofcourse, and this will not change at all. I have no problem whatsoever with Alexandria carrying condoms in her purse. But the point is that Alexandria will give you a condom when the MC looks like a female. Since the true gender is hidden at that time, she should have no reason to think that the MC is male. Note that the fix only changes the text, now mentioning that the MC carries a condom in her purse (just in case).
Keeping your true gender hidden is a main topic in some games (eWardrobe anyone?), so the casual 'Oh I knew right away that you're a guy' is a bit much here.

**Comment by AceXP** [comment]
Now merged to dev.
