### ISSUE TITLE
Dirty clothing icon missing in inventory

### ISSUE THREAD

**Issue by Innoxia** [Innoxia/liliths-throne-public#128]
Dirty clothing has an indicator icon overlaid while it’s equipped, but not when it the inventory.

**Comment by picobyte** [comment]
an attempt to address this: pull request #165
In buyback modus the cum splatters are still not visible. Does that also need to be fixed?
Also, shouldn't price decrease for cum-stained clothing?

**Comment by Innoxia** [comment]
Fixed in #165.

I don't think it matters too much if it doesn't display in the buyback menu - I'm going to be improving that part of the UI at some point. ^^

I will add a small price decrease for cum-stained clothing, good idea!
