### ISSUE TITLE
Minor text error giving money in harpy nests

### ISSUE THREAD

**Issue by Rydelfox** [Innoxia/liliths-throne-public#1291]
**Describe the bug**
When giving money to a harpy in the harpy nests, you line "Just promise to care of yourself, ok?" appears.
This is line 513 in .\res\txt\encounters\dominion\harpyAttack.xml

**Expected behavior**
Line should be "Just promise to take care of yourself, ok?"

**To Reproduce**
1. Defeat a harpy
2. Talk to them
3. Encounter them again
4. Give them money

**Attach files**

**Additional information:**
 - Game version 0.3.6.4
 - OS: Windows 8.1
 - Using .jar or .exe: .jar
- If using .jar, and you are not including an error.log file/text, please include your java version: 1.8.0_231-b11

**Comment by AceXP** [comment]
This has been fixed with a PR, could you check it and close this issue?

**Comment by Rydelfox** [comment]
Confirmed fixed
