### ISSUE TITLE
[0.3.6.8] Tail diameters are all wrong

### ISSUE THREAD

**Issue by TadUnlikely** [Innoxia/liliths-throne-public#1293]
**Describe the bug**
Tail diameters are all over the place. Rose has a tail diameter of -1 inch (that's a negative number) with a tail circumference of -4 inches. Lilaya has a tail diameter of 1 foot, 1 inch (3 feet and 4 inches in diameter.)

**Expected behavior**
Tail diameters should never be negative, and should probably fall within the expected parameters that match the penis diameters. Penis diameters appear to be correct so far. Based on what I'm seeing during sex, it looks like the numbers are wrong, not just descriptions.
 
**To Reproduce**
Please include the steps that need to be taken in order to reproduce the bug.
e.g.:
1. Get into the game
2. Inspect tail descriptions on various characters
3. See that they're crazy

**Attach files**
No errors.

**Additional information:**
 - Game version 0.3.6.8
 - OS: Linux
 - Using .jar or .exe:  .jar
- If using .jar, and you are not including an error.log file/text, please include your java version:  1.8.0_172

**Comment by Eliria** [comment]
Have you tried changing to metric to see if it's a unit conversion error?

**Comment by TadUnlikely** [comment]
Doesn't look like unit conversion - positive centimeters wouldn't convert to negative inches. Swapping to metric shows the same problem exists. There's something specific to tail dimensions that's not right, but I haven't been able to track it down yet.

**Comment by TadUnlikely** [comment]
It looks like this was probably corrected in 0.3.6.9, and is definitely corrected as of 0.3.9.9. Closing.
