### ISSUE TITLE
Major issue with sex action availability

### ISSUE THREAD

**Issue by Innoxia** [Innoxia/liliths-throne-public#130]
in version 0.1.99 when you are having sex with a futanari character. You can choose '' suck dick '' and '' eat out '' at the same time.

A futa is riding me cowgirl. Somehow, she still performed the 'anal tease' action. Cats are flexible, but not THAT flexible.

Something like that happened again. I've got Brax on all fours like a good doggy, and I chose the anal tease option... but the text that displayed was the text for teasing MY ass with HIS cock.

It seems to have no idea which character's in which position anymore.

need to check all sex positions - apparently sex actions are seriously messing up

**Comment by Innoxia** [comment]
You can, while fucking a succubus’ boob, kiss her breasts. That sounds anatomically unlikely for most people. Possibly with a “Flexible” trait you could get by being a cat, or something?

**Comment by Innoxia** [comment]
You can suck your tail while performing cunnilingus or analingus. This appears to be because these both block the tongue, but not the mouth. If you start out sucking a tail, you can’t eat someone out, as it apparently blocks both.

**Comment by Innoxia** [comment]
The NPCs are still very insistent on deepthroating their own tails while performing oral or otherwise actions.

**Comment by Innoxia** [comment]
Yeah, seems you both get the options the other partner have in addition to your own. The spitroasting scenes have had the same problem with not respecting position since they were introduced, though only for the NPCs as far as I can tell.

**Comment by Innoxia** [comment]
Kate's sex scene is bugged again. You always get the options for both positions, just like last time.

**Comment by Innoxia** [comment]
when your resisting and pushed onto your knees in the "kneeling" position, the standing char starts sucking your cock

**Comment by A-Master-of-Puppets** [comment]
This looks like two separate issues to me; one with actions that should be locked out by position, and one with actions that are OK by position, but shouldn't be possible at the same time.

**Comment by Innoxia** [comment]
Agreed; I'll get them both sorted out for the next version.

**Comment by Innoxia** [comment]
Additional report:
Mainly playing a submissive character is ruined now because NPC's are completely obsessed with fingering and hotdogging, regardless of their fetishes. The bug from the last patch still hasn't been fixed, where it's literally impossible for an NPC to do anal sex even if they have the anal fetish. They will always prioritize anal fingering, hotdogging or thigh sex.

**Comment by Innoxia** [comment]
Fixed the major problem with partner actions appearing for the player.

I'll close this as fixed, and open two new issues for:
1. Some actions are available in sex which shouldn't be possible at the same time.
2. AI in sex is too fond of fingering, and very rarely penetrated properly.
