### ISSUE TITLE
Cargo pants don't have camo patterns

### ISSUE THREAD

**Issue by master9147** [Innoxia/liliths-throne-public#1309]
**Describe the bug**

**Expected behavior**

**To Reproduce**
Please include the steps that need to be taken in order to reproduce the bug.
e.g.:

**Attach files**
Please either attach a copy of your error.log (in the LilithsThrone/data directory), or copy & paste the contents to the end of this bug report.

**Additional information:**
 - Game version [e.g. 0.3.2.5]
 - OS: [e.g. Windows 10]
 - Using .jar or .exe: [e.g. .jar]
- If using .jar, and you are not including an error.log file/text, please include your java version: [e.g. 1.8.0_172]

**Comment by AceXP** [comment]
This is possible for some time now. Can you please check and close this issue.
