### ISSUE TITLE
Occupants stop searching for a job when I load a game

### ISSUE THREAD

**Issue by Freimann01** [Innoxia/liliths-throne-public#1310]
**Describe the bug**
When I load a game, all friendly occupants living in my guest rooms will have all of the jobs in the 'suggest a job' section automatically deselected, making them abandon their job search. I can re-suggest jobs to them, and their job search works as intended until I load a game again. This happens both when I load a game from the main menu after exiting, as well as when I save the game and load it without exiting the game.

**Expected behavior**
Loading a game does not automatically deselect all suggested jobs.

**To Reproduce**
1. Get a friendly occupant to move into a guest room.
2. Save the game before they find a job.
3. Load the game you just saved.

**Attach files**
[error.log](https://github.com/Innoxia/liliths-throne-public/files/4277384/error.log)

**Additional information:**
 - Game version: 3.6.9
 - OS: Windows 10
 - Using .jar or .exe: .jar

**Comment by AceXP** [comment]
This has been fixed for some time, could you check it and close this issue?
