### ISSUE TITLE
Wrong text when reading a book in defeated enemy's inventory

### ISSUE THREAD

**Issue by Yapachi** [Innoxia/liliths-throne-public#1317]
**Describe the bug**
I have defeated a leopard in battle and read his book "Curious kitties". The game said: "The leopard produces a book, titled 'Curious Kitties', which he then forces you to read…". I am sure there is an error.

**Expected behavior**
Some text about me reading a book myself

**To Reproduce**
Please include the steps that need to be taken in order to reproduce the bug.

1. Defeat an enemy
2. Select a book in their inventory
3. Select "Read(self)"
4. Read the text

**Attach files**
Please either attach a copy of your error.log (in the LilithsThrone/data directory), or copy & paste the contents to the end of this bug report.

**Additional information:**
 - Game version [e.g. 0.3.2.5]
 - OS: [e.g. Windows 10]
 - Using .jar or .exe: [e.g. .jar]
- If using .jar, and you are not including an error.log file/text, please include your java version: [e.g. 1.8.0_172]

version 0.3.6.9, .exe x64

**Comment by AceXP** [comment]
This has been fixed in the latest version, could you check it and close this issue?
