### ISSUE TITLE
Game fails to identify player's race

### ISSUE THREAD

**Issue by RandomNecromancer** [Innoxia/liliths-throne-public#1329]
**Describe the bug**
After drinking a transformation potion to grow a unicorn horn and feathered wings, my character's race hasn't changed to alicorn

**Expected behavior**
My character's race should've changed to alicorn

**To Reproduce**
1. Drink a transformation potion to grow a unicorn horn and feathered wings
2. Check your race

**Attach files**
![Captura de Tela (1)](https://user-images.githubusercontent.com/45304526/80320349-4ea9bd80-87ec-11ea-8a3a-b96bd8fd2f92.png)

**Additional information:**
 - Game version 0.3.7.3
 - OS: Windows 10
 - Using .jar 
 - Java version: 1.8.0_251

**Comment by Innoxia** [comment]
This will be fixed in the next update, thank you for the report!
