### ISSUE TITLE
[0.3.7.3] Game sets all generic npcs ages to 18 on load.

### ISSUE THREAD

**Issue by Farmerrorry** [Innoxia/liliths-throne-public#1330]
Describe the bug
Loading any save made on version 0.3.7.3 will set all generic npcs (Muggers, Slaves, ect.) age back to 18.

Expected behavior
Npcs to have a consistent age when saving and loading the game.

**Comment by Innoxia** [comment]
I've got this fixed for the next update (and it will retroactively fix all altered ages upon loading a saved game, by using the NPCs unmodified 'conception' date). Thank you for the report!
