### ISSUE TITLE
[0.3.7.3] Harpy Nest description bug

### ISSUE THREAD

**Issue by LeechingLecher** [Innoxia/liliths-throne-public#1332]
The harpies are pacified, and having a friendly daughter in a tile results in the final paragraph being:

"Despite the potential for a harpy to swoop down and attack you, you feel quite safe in this area, as the only person you're likely to encounter is your daughter, Jeri…#ELSIF(!npc.​getAffectionLevel(pc).​isLessThan(AFFECTION_POSITIVE_ONE_FRIENDLY))Despite the potential for a harpy to swoop down and attack you, you feel quite safe in this area, as the only person you're likely to encounter is Jeri, who is on friendly terms with you…#ELSIF(pc.​isQuestCompleted(QUEST_LINE_SIDE_HARPY_PACIFICATION)You sometimes see an Enforcer patrolling a walkway off in the distance, reminding you that it's now safe for people to be travelling throughout the Harpy Nests.​ Although there's no risk of being attacked, harpies are still quite touchy by nature, and you imagine that it wouldn't be too hard to cause a confrontation if you were to go looking for trouble…"

**Comment by Stadler76** [comment]
That should be `#ELSEIF` instead of `#ELSIF` in [`liliths-throne-public/res/txt/places/dominion/harpyNests/generic.xml` (Line 259 and 261)](https://github.com/Innoxia/liliths-throne-public/blob/2089b64fa8548950e147fcf28be867a4d5d5fe8c/res/txt/places/dominion/harpyNests/generic.xml#L259).

**Comment by Innoxia** [comment]
This will be fixed in the next update, thank you for the report!
