### ISSUE TITLE
0.3.8 Bug inventory 

### ISSUE THREAD

**Issue by Max-im-us** [Innoxia/liliths-throne-public#1345]
Description of Bug:
When I try to unequip the weapon, it is not unequip, but is copied to the inventory many times.
Additional information:

    Game version: 0.3.8
    OS: Windows 10
    Using .exe
    Java 1.8.0_172
link to save: [https://mega.nz/file/pQUwxSAQ#aKoPQve4VtmdCTamBlEzcvO7NlQtcFlO5VXLr1Hlf-w](url)

**Comment by Innoxia** [comment]
Thank you for the report, this should be fixed in the v0.3.8.1 hotfix.
