### ISSUE TITLE
Non-Consent Bug

### ISSUE THREAD

**Issue by xPURExRain** [Innoxia/liliths-throne-public#1347]
As of this latest build, I have an individual slave named Christine who despite having the fetish for enjoying having sex with people who are resisting, is instead losing a fair bit of lust when it occurs. So far this has only been tested with a NPC having perk instigating sex with player to be true. Save file included for testing.

[Seria Error.zip](https://github.com/Innoxia/liliths-throne-public/files/4711634/Seria.Error.zip)

**Comment by Innoxia** [comment]
This has been addressed by #1417
