### ISSUE TITLE
Harpy dialog missing, incorrect path that doesn't point to harpy file

### ISSUE THREAD

**Issue by Eliria** [Innoxia/liliths-throne-public#1353]
Have a #1354
**Describe the bug**
Some of the harpy encounters were throwing a missing content error because the code was referring to the path for alleywayAttacker content but looking for harpy-specific entries like HARPY_PEACEFUL_TALK. 

**Expected behavior**
Returns harpy dialog from harpy content files instead of the alleywayAttack encounter file.

**To Reproduce**
Talk to rng harpies that are peaceful. A few other entries didn't work, believe paying off and offering companions also has same glitch.

**Additional information:**
 - 0.3.8.1
 - OS: Win7

PR: Made semantic changes in the harpydialog code to use the getFileLocation function for all instances of looking for dialog, as opposed to some drawing from non-harpy files using the literal path to encounter/dom/alleywayAttack, and others using the getFileLocation to figure out which harpy dialog file to draw off. Because the harpyStorm (actually both storm files) content file is missing several entries that is still valid during a storm those relevant entries were duplicated from harpyAttack to the harpyAttackStorm file to prevent more missing dialog errors due to the getFileLocation drawing from the Storm file for entries not in it.
The only issue I see with this change is making editing of the dialog entries messier because it's got to be updated to multiple content files, but I feel like it's still better to use a function for all of the path logic, and either deal with overlap or customizing the flavor text more for entries, or improve the function to draw from a generic default source instead of the area/storm specific sources for those entries that use a default.

**Comment by AceXP** [comment]
This has been fixed in version 0.3.8.5, so please check it and close this issue.

**Comment by Eliria** [comment]
Thought this was closed already. I cast you to the void from which you came, ticket!
