### ISSUE TITLE
Custom Slave's Perk Bug

### ISSUE THREAD

**Issue by MrAhegao** [Innoxia/liliths-throne-public#1355]
If you custom your own slave in 'Helena's Boutique' - this slave won't have an opportunity to study perk tree. The problem here is that the main three perks, which have to be already available are not learned by default, so you can't progress perk tree or even start it, because game will tell you, that you requires **connecting** perks.

screenshot:
https://i112.fastpic.ru/big/2020/0612/c5/5e9761ea38b15ed060c6353dc8bebfc5.png

**Additional information:**
 - Game version [e.g. 0.3.8.1]
 - OS: Windows 10
 - Using .exe:]

**Comment by MrAhegao** [comment]
Ok, i've fix it, you need simple 'Reset perks", so main perks become available.

**Comment by AceXP** [comment]
This has been fixed in version 0.3.8.5, so please check it and close this issue.
