### ISSUE TITLE
[0.3.8.6] Cum Regeneration

### ISSUE THREAD

**Issue by DocAmakus** [Innoxia/liliths-throne-public#1362]
**Describe the bug**
Disabling cum regeneration does not work as intended. If you turn it off cum eventually goes to empty balls and stays on empty balls until you turn it back on and then back off.

**Expected behavior**
Disabling cum regeneration should keep cum full always as per the description.

**To Reproduce**
Please include the steps that need to be taken in order to reproduce the bug.
e.g.:
1. Turn off cum regeneration 
2. Play for awhile
3. Cum regeneration breaks

**Attach files**
https://imgur.com/a/wuXWE5o

**Additional information:**
 - Game version 0.3.8.6
 - OS: Windows 10
 - Using .exe

**Comment by AceXP** [comment]
Can this issue be closed now? If so, please close this issue.
