### ISSUE TITLE
Save enabled in Brax dialogue

### ISSUE THREAD

**Issue by Innoxia** [Innoxia/liliths-throne-public#137]
Found a bug with the Brax. After beating him in combat I quicksaved during the conversation and continued. Later I quickloaded, and found myself at post-combat hitpoints (almost dead) but Brax immediately behaved as if I had re-entered the room and went straight to combat.

**Comment by A-Master-of-Puppets** [comment]
Quicksave, and overwriting existing saves, are available most of the time. Only the _new_ save button is disabled during dialog.

**Comment by Innoxia** [comment]
This has been fixed.
