### ISSUE TITLE
[0.3.8.9] Aura is calculated incorrectly

### ISSUE THREAD

**Issue by MedukaMeguca** [Innoxia/liliths-throne-public#1374]
**Describe the bug**
The Maximum Aura is calculated incorrectly at low Arcane levels. A character's Arcane stat and level are not taken into the calculations for Maximum Aura when the Arcane stat is between 10 and 14. Likely a remnant from earlier game versions where Arcane levels (Impotence, Potential, Proficiency, etc.) had different numerical ranges than in the present version. In an earlier version, Arcane Potential had a range of 5-15 and included an "Aura limited to 5" effect, which in the current version should only apply to Arcane Impotence.

**Expected behavior**
Maximum Aura should be calculated based on a characters Arcane stat in the following way:

Arcane < 10
Maximum Aura set to 5

Arcane 10 or higher
Maximum Aura is calculated according to 5 + (2*level) + (5*Arcane) + Bonus Aura

How it is actually calculated in game:

Arcane < 10
Maximum Aura set to 5

Arcane between 10 and 14
Maximum Aura is calculated according to 5 + Bonus Aura

Arcane 15 or higher
Maximum Aura is calculated according to 5 + (2*level) + (5*Arcane) + Bonus Aura

**To Reproduce**
1. Set a character's Arcane stat to a value between 10 and 14 inclusive
2. Observe the resulting Maximum Aura

**Comment by AceXP** [comment]
This is fixed in version 0.3.9.1, could you check it and close this issue?
