### ISSUE TITLE
Can't manage slave's job

### ISSUE THREAD

**Issue by phiadawer** [Innoxia/liliths-throne-public#1378]
**Describe the bug**
An error message appears instead of job management menu.

**Expected behavior**
Job management menu should appear.

**To Reproduce**
1. Walk up to a slave or click "Manage people" in your room
2. Click on "Manage > Job" or "Select slave's job"
4. See error "Error: getContent() method is throwing an exception in the node: 'Alex's Job'"

**Attach files**
[error.log](https://github.com/Innoxia/liliths-throne-public/files/5030334/error.log)

**Additional information:**
 - Game version: 0.3.9
 - OS: Windows 10
 - Using .jar

**Comment by aeipa** [comment]
I'm having the exact same problem :/ Hopefully it gets fixed soon

**Comment by AceXP** [comment]
This has been fixed in version 0.3.9.1, so please check it and close this issue.

**Comment by phiadawer** [comment]
Yes, everything is great in 0.3.9.1. I even used a save file from 0.3.8.9 and everything works smoothly.
