### ISSUE TITLE
Bug: Stealing Items From Vendors?

### ISSUE THREAD

**Issue by Demaar** [Innoxia/liliths-throne-public#1382]
There is a bug with the shop menu now.
Here is how to replicate it.
Requirements: Min 1 Consumable, Some Arcane essences.
1. Enter the shop menu of any Vendor
2. Click on your consumable (i.e. a bubblegum lollipop)
3. Click on Enchant
4. Click on the "Add" button over the output image
5. Click on "Craft"
6. Keep clicking "Craft" until you run out of the chosen consumable

Result: As soon as you run out of the consumable you will be sent back to the shop menu.
However, now it will have gone from a Buy/Sell menu to a trade menu.
This means you can simply take all of the Vendor's items at no cost.

Note: This Is a repost from a comment on the blog since the 0.3.9.1 hotfix did not fix this issue.

**Comment by AceXP** [comment]
This should have been fixed in version 0.3.8.6, but I can confirm that this is still possible in the latest version.

**Comment by Demaar** [comment]
According to the changelog of V0.3.9.4, this is now fixed.

**Comment by AceXP** [comment]
Yes, I can confirm that it has been fixed.
