### ISSUE TITLE
Can't run on OpenJDK 11

### ISSUE THREAD

**Issue by Yowlen** [Innoxia/liliths-throne-public#1390]
**Describe the bug**
It refuses to run on OpenJDK 11.0.8, instead, throwing an error:
> Error: Could not find or load main class com.lilithsthrone.main.Main
> Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

**Expected behavior**
I expect it to start up and show a window or something? Idk, first time trying to play this.

**To Reproduce**
1. Install OpenJDK 11
2. Use it to run the .jar file

**Attach files**
Please either attach a copy of your error.log (in the LilithsThrone/data directory), or copy & paste the contents to the end of this bug report.

Obviously I can't do either of this since it's not even executing to begin with and there's nothing to display that isn't text output from the command line.

**Additional information:**
 - Game version: 0.3.9.1
 - OS: Xubuntu 20.04
 - Using .jar or .exe: .jar
- If using .jar, and you are not including an error.log file/text, please include your java version: Output of `java --version`:
> openjdk 11.0.8 2020-07-14
> OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
> OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)

**Comment by AceXP** [comment]
Dev-note: This project is relying on JavaFX which isn't included in the Openjdk, which is often the common choice for Linux enthusiasts. If you're using Linux, please make sure to use the Oracle JDK to build this project or install OpenJFX.

Did you see this?

**Comment by Yowlen** [comment]
Ah. I wasn't aware of the differences between OpenJDK and Oracle's Java, nor did I notice that (since I downloaded from the blog and kinda skipped the readme here). Thanks. I figured out how to get OpenJFX to work, but now there's a new problem:

[error.log](https://github.com/Innoxia/liliths-throne-public/files/5067303/error.log)

**Comment by AceXP** [comment]
There is a 'no jfxwebkit in java.library.path' message. Maybe you need to add JFX to this path too?

**Comment by Yowlen** [comment]
Thanks for the suggestion. I did a little digging and worked out how to add JFX to that path, but it's still giving the same errors afterwards.

As for Discord, I'd much rather not. It's sorta an accessibility issue with my ADHD. I don't do well in group chats. The extra chats that aren't related to my issue would only serve to distract and overwhelm me.

Looking through the log some more, it appears to be a rendering fault, so maybe it's a GTK issue? Given that I'm using Xfce4 as my desktop environment, which primarily uses GTK2, and I remember reading during my searches something about how either OpenJFX or OpenJDK defaults to GTK3, maybe it's a missing GTK3 dependency. Dunno how to go about narrowing that down or switching to GTK2, though. Will have to either research more or wait for more suggestions, or maybe just switch to Oracle's Java instead.

Regardless, though, thanks so much for the help.

**Comment by CognitiveMist** [comment]
Would you mind uploading your error.log, to show whichever errors you are currently experiencing? I personally don't know much about GTK troubleshooting, but I do know JavaFX moderately well.

**Comment by Yowlen** [comment]
As I said, the error.log I posted in my first reply up above is the same both before and after adding OpenJFX's library folder to the java.library.path variable.

And yes, I already use the --add-modules argument. The full command line after compensating for OpenJFX is:
`java -jar --module-path /usr/share/openjfx/lib --add-modules=javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.media,javafx.swing,javafx.web ./LilithsThrone_0_3_9_1.jar`

Every OpenJFX module in that folder is listed there, so there's nothing that could be missing that is required by the game.

**Comment by CognitiveMist** [comment]
Ok, thanks for clarifying. The root issue according to that log seems to be:
`Caused by: java.lang.UnsatisfiedLinkError: no jfxwebkit in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]`

And now that I've typed that, this does ring a bell. There is an ubuntu bug [A] that describes a similar problem, and according to both that bug, and a stackoverflow question [B], people were able to work around it by using the debian package [C].

Perhaps that will give you the solution to this problem.

[A] https://bugs.launchpad.net/ubuntu/+source/openjfx/+bug/1877000
[B] https://stackoverflow.com/questions/62283263/davmail-no-jfxwebkit-in-java-library-path
[C] https://packages.debian.org/sid/amd64/libopenjfx-jni

**Comment by Yowlen** [comment]
Awesome! Thanks. Installing the `libopenjfx-jni` and `libjpeg62-turbo` packages from the Debian sid repos allowed it to work.

I guess we can mark this as closed now. Thanks again. ^_^
