### ISSUE TITLE
8/20 Dev version never assigns equine names

### ISSUE THREAD

**Issue by Rydelfox** [Innoxia/liliths-throne-public#1395]
In the dev versions, name.java:723 currently reads:
} else if(r==Race.REINDEER_MORPH) {
However, this is the check for using the equine name list
The line should be
} else if(r==Race.HORSE_MORPH) {

**Comment by AceXP** [comment]
This should be fixed in the next version, can you check it and close this issue?

**Comment by Rydelfox** [comment]
Tested and confirmed fixed
