### ISSUE TITLE
Inaccuracies in americanEnglishConversions

### ISSUE THREAD

**Issue by Rydelfox** [Innoxia/liliths-throne-public#1396]
Some of the text converted in the americanEnglishConversions function for tourists is incorrect

savoury should become savory - currently becomes savoury
manoeuvre should become maneuver - currently tries to become both manoeuver and maneuvre, both incorrect
epilogue, monologue, and prologue should be unchanged - currently becomes epilog, monolog, and prolog.
oestrogen should become estrogen. Currently becomes oestrgen
mementoes should becomes mementos. Currently becomes mementes

It would probably also be a good idea to include the following conversions for words used in game but not currently covered by the translator:
parlour -> parlor
apologise -> apologize
queue -> line

From the use of "epilog," "monolog", and "prolog," I suspect you might be using Collins English Dictionary for these. It contains a number of "American" spellings that don't match actual American spellings.  American Heritage Dictionary may be a better resource.

**Comment by AceXP** [comment]
This is fixed in the 0.4.0 version, could you check it and close this issue?

**Comment by Rydelfox** [comment]
Confirmed fixed
