### ISSUE TITLE
Various bugs for version 3.9.9

### ISSUE THREAD

**Issue by TheWeirdling** [Innoxia/liliths-throne-public#1418]
Penis urethra depth is unusually high:

  It's minimum value seams to be penis length x 1.5 and increasing to several times the length of the penis (maybe x5 or x7).  This seams unintentional and results in values that are inconsistent with other orifice penetration depths.  

Constable encounter:

a few times I encountered the constables the code referencing the player did not display the player name/attributes in the dialog and instead gave a function reference error.

Unexpected slave in stocks behavior:

A randomly generated slave in the stocks was listed as being available for vaginal use.  This slave didn't have a vagina and was a feminine, breasted slave with a penis.  The slave got the risk of pregnancy status effect from being in the stocks and eventually became pregnant before they were naturally shuffled out of the game.

**Comment by TheWeirdling** [comment]
Not a bug per say but something that might want to be refactored:

Ally way transformers who want to change your species currently do not prioritize changing your characters arms or legs to fit the species they want.  This can make being transformed into another species very random/unreliable if you have a lot of enchantments that change your characters physical measurements.  Even with the test subject fetish it is very unlikely to have your arms or legs changed instead of the measurements of various body parts (I didn't witness character arm or leg transformations for at least 15 forced transformations before they were targeted).

**Comment by AceXP** [comment]
The error with dialogues in encounters with Enforcers should be fixed in the next version.

For the other errors, it is generally better to have one issue for each error, so they can be kept tracked of seperately.

**Comment by ckcazza** [comment]
Been having an occasional problem while playing where the game just stops letting me save. Timing varies, and location doesn't seem to matter either.

**Comment by AceXP** [comment]
@ckcazza : Not being able to save has been reported before, I think. But without an indication as to where or when, it's impossible to track down. It's not possible to save everywhere, but you are probably aware of this? Is there anything in the error log? How long were you playing, and what were you doing in the game? Would it be possible to upload a save game file, so this can be investigated further?
Note: opening a new issue rather than commenting on an existing issue makes it easier to keep track of things.

**Comment by AceXP** [comment]
The issue with slaves in the stocks having permissions they shouldn't have should be fixed with PR #1426 'Change default permissions/job settings allocation'.

**Comment by TheWeirdling** [comment]
Would it be helpful for me to closet this thread to help the devs manage bugs?  If so what issues from my original posts till need to be addressed so I can make separate threads for them?

**Comment by AceXP** [comment]
Yes, having each bug in a separate issue helps with keeping track.

The penis urethra and the tf arm/leg priority are still to be dealt with.

@ckcazza the same goes for the issue with saving the game, but more information is still needed.
