### ISSUE TITLE
Slave Milking equipment will remaind attatched after some slaves finish their milking session

### ISSUE THREAD

**Issue by TheWeirdling** [Innoxia/liliths-throne-public#1429]
**Describe the bug**
Slaves who have their clothing pushed out of the way during milking will sometimes keep their milking pumps attached indefinitely.

**Expected behavior**
Milking equipment should be removed after milking finishes.

**To Reproduce**
It isn't clear to me why some of my characters are having this problem and others are not.  I've included a save file with a demon who keeps getting their milking equipment stuck to their body.  This problem started happening after I equipped the slave with the kitty lingerie set.  Another character, a bat morph named pip does not seam to have this problem but is also clothed.  

**Attach files**

[Test Save.zip](https://github.com/Innoxia/liliths-throne-public/files/5331620/Test.Save.zip)

**Additional information:**
 - Game version 3.9.9
 - OS: Windows 10
 -  .exe

**Comment by AceXP** [comment]
I had a look at this and under normal circumstances the equipment gets disposed off for both slaves.

There is however something to keep in mind, and that is that slaves will interrupt their normal schedule if the MC is in the same place. This could lead to a situation where the slave will miss the 'end of job' status update (which happens each hour on the hour) and thus get stuck with the milking equipment. The idea being that if the MC is in the same place there could be some interaction going on, so the update is skipped to prevent the slave from just disappering in the middle of that.

**Comment by AceXP** [comment]
This should work better in version 3.13 (but keep in mind that being in the same place as the slave might still influence it).

**Comment by AceXP** [comment]
Does this still happen? If so, please give an example of how and when this happens, what the MC is doing etc. If not, could you please close this issue?
