### ISSUE TITLE
Suggestion: Cum Stud should make slaves with penises enjoy being milked

### ISSUE THREAD

**Issue by TheWeirdling** [Innoxia/liliths-throne-public#1430]
Given the description for cum stud as one where the character loves cumming and filling everything with their cum, it might make sense that slaves with this fetish gain positive affection from being used in the milking stalls, especially if they have a penis.

**Comment by AceXP** [comment]
This makes sense and PR #1344 should take care of this (but that PR is outdated at the moment though).
