### ISSUE TITLE
Double anal creampie doubles sperm count

### ISSUE THREAD

**Issue by AlexDevolio** [Innoxia/liliths-throne-public#1432]
Sorry for my bad english

**Describe the bug**
During Double anal creampie, the amount of sperm in the ass of each of the submissives is the same as that erupted from the dominant

**Expected behavior**
Sperm count received by the submissives should have been less than (or equal to) half the emitted value

**Attach files**
Screenshot below

**Additional information:**
 - Game version 0.3.9.9
 - OS:  Windows 10
 - Using .exe

![Screenshot](https://user-images.githubusercontent.com/72670346/95664414-4baf4900-0b50-11eb-9be9-1ce7afdf076f.JPG)

**Comment by AceXP** [comment]
Actually the amount for each character on the receiving end is correct, as it is half the normal amount. However, the total amount is also halved and this is not correct. There is an easy solution, so hopefully it will be fixed in a later version.

**Comment by AceXP** [comment]
This should be fixed in version 3.13, can you check it and close this issue?
