### ISSUE TITLE
Npc  foot fetish actions

### ISSUE THREAD

**Issue by Kon1399** [Innoxia/liliths-throne-public#1433]
**Describe the bug**
Don't know if it's just me, but while I play as sub, partner doesn't perform any feet related fetish it has. Never. And even if dom, partners won't do anything(I checked options, all enabled). I've also checked few other fetishes, they're fine.

**To Reproduce**
- (eg.)Get attacked by nps with foot fetish (sub or dom, both doesn't work)
- lose or submit 

**Additional information:**
 - Game version 0.3.9.9

**Comment by AceXP** [comment]
Getting a NPC to give a footjob works for me. Bree has a dominant foot fetish here. Also, and this is important, the character receiving the footjob needs to have a positive desire for the submissive foot fetish. With a neutral or negative desire it won't work. For giving a NPC a footjob it works the same, but the fetishes are ofcourse reversed.
Footjobs only work with a penis too, and not any other bodypart.

I hope that helps, could you check it and close this issue if you get it to work?

![Footjob](https://user-images.githubusercontent.com/56754746/96182215-7412bb00-0f35-11eb-8b40-f441bdff39bb.png)

**Comment by Kon1399** [comment]
+AceXP
Thanks, i didn't know it works that way now. I skipped few versions so that's new for me. Still, it's a little bit odd, 'couse other fetishes doesn't require from you to have it  for NPC's playing with you as they want.
