### ISSUE TITLE
Impossible challenge with Constable Hughes (Sean)

### ISSUE THREAD

**Issue by AlexDevolio** [Innoxia/liliths-throne-public#1434]
And again, sorry for my poor english

**Describe the bug**
There is only one chance to challenge Sean. If you change your mind, you can't challenge him again.

**To Reproduce**
1. Talk to Constable Hughes in Slaver Alley
2. Choose "Complain"
3. Then "Persist"
4. Then "Challenge"
5. Change your mind via "Back out"
6. Return to Constable Hughes and repeat steps 1-4
7. See that option "Challenge" does not work

**Additional information:**
 - Game version 0.3.9.9
 - OS: Windows 10
 - Using .exe

**Comment by AceXP** [comment]
Sean cannot be challenged a second time because there is an issue which leads to a nullpointer exception. A fix is underway.

**Comment by AceXP** [comment]
This should be fixed in version 3.13, can you check it and close this issue?
