### ISSUE TITLE
Summoning Arcane elemental does not work (java.lang.NullPointerException)

### ISSUE THREAD

**Issue by brogowski** [Innoxia/liliths-throne-public#1440]
**Describe the bug**
Summoning Arcane elemental does not work (nothing happens when summoning on map) and breaks UI (cannot end turn when summoning in combat).

**Expected behavior**
Elemental pops up I guess?

**To Reproduce**
1. Go into combat
2. Click on summon arcane elemental
3. Click on End Turn button
4. Nothing happens (i.e. turn does not end)

**Attach files**
[error.log](https://github.com/Innoxia/liliths-throne-public/files/5454749/error.log)

**Additional information:**
 - Game version [0.3.9.9]
 - OS: [Windows 10]
 - Using: [.exe]

**Comment by CognitiveMist** [comment]
This seems to be caused by invoking `getSummoner()` on an Elemental before the summoner is set.

**Comment by brogowski** [comment]
Turns out it breaks only during Arcane storm.

**Comment by AceXP** [comment]
Since this was fixed by Innoxia some time ago, could you check it and please close this issue?

**Comment by brogowski** [comment]
It works with 0.3.20 version 👍
