### ISSUE TITLE
Stuck in the Enforcer HQ

### ISSUE THREAD

**Issue by Noidiz** [Innoxia/liliths-throne-public#1446]
Every time i defeat Brax, even when i started a new game, i hit Outside to leave but the menu for taking the enforcer outfit doesnt go away. I tried opening my phone and fast traveling somewhere, but it wont work.

I just want the bug fixed because i enjoy the game, yet i cant play past a certain point because i cant leave Domimon, and i dont have any other sidequests.

Fight Brax and win. It may have somthing to do with loosing the fight the first time.

Game version 0.3.9.4
OS Windows 10

**Comment by AceXP** [comment]
This bug is known and has been fixed in version 0.3.9.8. As a workaround, play with autosave on and load the autosave after hitting the 'outside' button. That should let you continue the game.
If that works for you please close this issue.
