### ISSUE TITLE
Clothing colours not saving

### ISSUE THREAD

**Issue by Innoxia** [Innoxia/liliths-throne-public#145]
BUG -- In this version (including hotfix), it would seem that dying secondary and tertiary slots is broken. If you save a game with any clothing that you have dyed the secondary and tertiary slots for, then when you reload the game the colors get reset to default. I'm guessing this might be a save compatibility issue, as the reset only occurs after any reload (not travel from room to room).

**Comment by A-Master-of-Puppets** [comment]
#147 should fix this.

**Comment by Innoxia** [comment]
Thank you!
