### ISSUE TITLE
[0.3.13 alpha] Summoned Elemental's Combat Moves randomly assigned

### ISSUE THREAD

**Issue by LeechingLecher** [Innoxia/liliths-throne-public#1464]
**Describe the bug**
Your summoned elemental will randomly re-select 8 available moves every combat, regardless of anything you set under Combat Moves in their menu.

**Expected behavior**
Our elemental should only have the moves we assign under Combat Moves, and that selection should not change.

**To Reproduce**
1. Have an elemental summoned.
2. Set elemental's Combat Moves in passive or active form.
3. Enter combat.
4. Look at elemental's Combat Moves again.

**Additional information:**
 - Game version 0.3.13 alpha
 - OS: Windows 10
 - Using .exe

**Comment by AceXP** [comment]
Looks like they are not excluded anymore from doing a reset for their moves. Should be easy to fix.

**Comment by AceXP** [comment]
This should work properly now in version 0.3,20. Could you check it and close this issue?

`Fixed issue where the combat moves of the player's elemental were reset. (by AceXP)`
