### ISSUE TITLE
bodySize assign syntax typo, space between dot ref

### ISSUE THREAD

**Issue by Eliria** [Innoxia/liliths-throne-public#1476]
https://github.com/Innoxia/liliths-throne-public/blob/cd1754acc1935958d84ae80cd4a174ef257df1f9/src/com/lilithsthrone/game/character/body/Body.java#L299

I have concern

**Comment by AceXP** [comment]
It's fully legal to write it like that, as Java ignores whitespace.

For example, you could also write

		bodySize
				= 
				builder
						. 
						bodySize
		;
