### ISSUE TITLE
Clitoris size "Big" button at character creation doesn't work

### ISSUE THREAD

**Issue by RandomNecromancer** [Innoxia/liliths-throne-public#1477]
**Describe the bug**
Clitoris size "Big" button at character creation doesn't work.

**Expected behavior**
To be able to select "Big" as clitoris size at character creation.

**To Reproduce**
1. Start a new game as a female
2. Advance to the character creation screen 
3. Click the "Vagina" button
4. Click the "Big" button under clitoris size

**Attach files**
Error.log:
Warning: getClosestStringMatch() did not find an exact match for 'innoxia_gun_western_kkp'; 
returning 'innoxia_gun_western_ppk' instead. (Distance: 3)

**Additional information:**
 - Game version: 0.3.13
 - OS: Windows 10
 - Using .jar, 
 - Java: 1.8.0_271

**Comment by AceXP** [comment]
There is a simple solution, should be fixed in the next version.
