### ISSUE TITLE
Popups are turning up empty all too frequently. on everything.

### ISSUE THREAD

**Issue by whiskeyfur** [Innoxia/liliths-throne-public#1478]
**Describe the bug**
Mouseover popups are often appearing empty.

**Expected behavior**
Mousing over many items will randomly work. Example, I saw the contents of one popup in the perk tree, then all the other popups for the next 15-20 items I needed to look at had empty boxes for information

**To Reproduce**
In about any screen that has information you can only find in popups, mouse over and then mouse out from that item.
Mouse back over the item and often enough the popup box will be empty.

**Attach files**
![lt_bug](https://user-images.githubusercontent.com/3805521/103927149-c0057400-50ce-11eb-9acc-7551d4ef1079.png)
[error.log](https://github.com/Innoxia/liliths-throne-public/files/5783193/error.log)

**Additional information:**
 - Game version: 0.3.6.1 A
 - OS: Windows 10 home
 - Using .jar or .exe: Jar
- If using .jar, and you are not including an error.log file/text, please include your java version: [e.g. 1.8.0_172]

**Comment by whiskeyfur** [comment]
Just tested with 0.3.13. The same bug exists there as well.

**Comment by AceXP** [comment]
This has already been reported, see Empty Tooltips #1444

As a workaround, use the .exe, or use an earlier version of Java.

**Comment by whiskeyfur** [comment]
Noted. I searched for "popups", not "tooltips". My mistake.
