### ISSUE TITLE
Addictions not saving properly

### ISSUE THREAD

**Issue by Innoxia** [Innoxia/liliths-throne-public#150]
Bug: It appears addictions are missing from slaves after loading a save, so something in the save or load process is not quite right.
Reproduction(ha!): 
1. have addictive & psychoactive cum
2. get blowjob from slave
3. slave gets "cummy meal" and "addicted to human cum" status applied
4. move around a few squares, view slave, both status from step 3 still applied
5. save game, reload game either immediately or after closing and reopening program
6. "cummy meal" status still applied to slave, "addicted to human cum" status missing.

**Comment by teutonicdude** [comment]
More data on this bug. From looking at the save data it looks like addiction info is getting saved but not loaded, as reloading a save and making a new save causes the addiction info to go missing. I'll look at the code to see if I can find the cause :D

**Comment by Innoxia** [comment]
Fixed :3 
Thank you for the info @teutonicdude - I started where you suggested things were going wrong, and quickly found the cause of the problem! ^^
