### ISSUE TITLE
Bug: Shopkeepers missing from stores - but stores/scenes still working. (Updated, more widespread than I realised)

### ISSUE THREAD

**Issue by Candycanes** [Innoxia/liliths-throne-public#1502]
I noticed whilst wandering around the Shopping Arcade that all of my shopkeepers except Nyan had dissapeared, all of their interactions work as normal in their own shops but all of their icons are missing and within the stores it says 'Characters Present None'. After checking around the area all of them seem to have congregated in the empty shop on the bottom left of the Shopping Arcade, I have no idea why, when or how this happened and loitering around or going home and sleeping doesn't seem to fix.
Edit: I just realised Kate is missing entirely from the map.

Image of the map with all shopkeepers (except Nyan) congregating in bottom left empty shop.
https://imgur.com/a/Mjgc3Wj

**Comment by Candycanes** [comment]
https://imgur.com/a/wIgcKBg
Still no closer to what is triggering this, but it is now occuring in the harpy nests as well (has moved Lexi + max as well as Diana and Harley to different tiles, the events quests/sex scenes still trigger on their nest tiles however same as with the shopkeepers in the mall)
Likely this means all maps are being affected and so this might be a bigger problem than I originally thought, even though I still have no idea what I'm doing to trigger it.

**Comment by AceXP** [comment]
In version 0.3.20 this should now work without problems again. There was a fix done in 0.3.18 for this issue (and related ones). Could you check it and close this issue?

`Fixed issue with NPCs sometimes having their home location set to seemingly-random tiles. This was mainly affecting Enforcer patrols (who had their home set to Candi's desk) and Wes and Elle (who had their home set to the HQ's waiting area).`

**Comment by Candycanes** [comment]
**Loading a save where the problem already occured continues to have the same issue**
However from gameplay on a new save I haven't encountered this issue repeating. I'll close for now and open it again if I encounter it.

**Comment by AceXP** [comment]
For a save where this problem exists it should revert to normal on the next day (after 24 hours), as it is linked to the day/night cycle.

**Comment by Candycanes** [comment]
I can confirm it does not. Shopkeepers are still displaced and congregating in the corner of the building no matter how many days I wait.
