### ISSUE TITLE
Build fails due to changelog string too long

### ISSUE THREAD

**Issue by TadUnlikely** [Innoxia/liliths-throne-public#1508]
**Describe the bug**
When attempting to build in Linux using maven, the build fails:
[ERROR] /home/foo/DEV/liliths-throne-public/src/com/lilithsthrone/main/Main.java:[98,17] constant string too long

This is the patchnotes variable. It may be failing due to my system being UTF8, but this is going to become a problem no matter what character set is in use at some point in the future.

**Expected behavior**
The build should succeed. The patch notes need to be moved out to an external text file and read in, rather than being set as a constant string.

**To Reproduce**
Please include the steps that need to be taken in order to reproduce the bug.
e.g.:
1. Clone the repo on a system that is set to use UTF8 by default
2. mvn package
3. See error

**Attach files**
Please either attach a copy of your error.log (in the LilithsThrone/data directory), or copy & paste the contents to the end of this bug report.

**Additional information:**
 - Game version 0.3.18
 - OS: Slackware -current Linux
 - Using .jar or .exe: Build failure, no jar produced
- If using .jar, and you are not including an error.log file/text, please include your java version:  1.8.0_251

foo@bar:~/DEV/liliths-throne-public$ mvn package
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------------< com.lilithsthrone:game >-----------------------
[INFO] Building lilithsthrone 1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ game ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1424 resources to com/lilithsthrone/res
[INFO] Copying 1848 resources to /home/foo/DEV/liliths-throne-public/target/res
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ game ---
[INFO] Compiling 216 source files to /home/foo/DEV/liliths-throne-public/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/foo/DEV/liliths-throne-public/src/com/lilithsthrone/main/Main.java:[98,17] constant string too long
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12:35 min
[INFO] Finished at: 2021-02-21T11:05:30-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project game: Compilation failure
[ERROR] /home/foo/DEV/liliths-throne-public/src/com/lilithsthrone/main/Main.java:[98,17] constant string too long
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by AceXP** [comment]
Known error, according to Innoxia:

Just delete the patch notes in Main.java
That should fix it
delete from line 233 to 831

i.e. Patch notes for v0.3.15 and earlier can be removed form the text.

**Comment by Midlight25** [comment]
Perhaps you can export that information to a text file instead? And then have the program read that information when it comes time to display the patch notes? That way, you don't have to lose all of that information?

**Comment by AceXP** [comment]
In version 0.3.20 a StringBuilder is used for the patchnotes, so this error will not happen now. Besides that, there is PR #1511 to handle the patchnotes as external files.

So I think this can be closed now. The patchnotes have always been a rolling window, where new versions get added at the top, and the oldest versions drop off at the bottom. Storing them as external files will have the advantage that the oldest ones are not lost permanently anymore.

**Comment by AceXP** [comment]
This is fixed in the 0.4.0 version, could you check it and close this issue?

**Comment by TadUnlikely** [comment]
Confirmed fixed as of 0.4.0!
