### ISSUE TITLE
Self-stroking handjob climax

### ISSUE THREAD

**Issue by Freimann01** [Innoxia/liliths-throne-public#1509]
This is actually two bugs, but I'm guessing that they are very related. The first happens in sex with a partner, the second happens when masturbating.

- In partner sex, if a character orgasms while stroking their own cock, the "handjob climax" option will describe them cumming into their own hands, but their partner's hands are the ones that end up dirty. This is true for both PCs and NPCs.
- In masturbation, the "handjob climax" option is not even available when stroking your own cock.

**Additional information:**
 - version 0.3.18
 - Windows 10
 - .exe

**Comment by AceXP** [comment]
This is fixed in the 0.4.0 version, could you check it and close this issue?
