### ISSUE TITLE
Game freeze/crash on anal sex

### ISSUE THREAD

**Issue by MonsterButler** [Innoxia/liliths-throne-public#1513]
So, on more than a few occasions now, with different pairings of PCs & NPCs, the game seems to "freeze" when having anal sex. Any buttons that would continue the sex scene fail to work, while every other button (like accessing options menu) seems to work fine. Occasionally accessing a menu like this will cause the sex scene buttons to disappear entirely or just make every button fail to work. Most of the time this has happened when either PCs and NPCs have an orgasm on the receiving end of anal, but I've also had the buttons lose functionality other times during anal.

The "expected behavior" here obviously is that the buttons should keep working as intended and allow the player to continue playing as usual. 

To reproduce...
1. Initiate anal sex with an NPC, does not matter if the PC is on the receiving or giving end
2. If it doesn't freeze on the start of the anal, keep going until whoever's on the receiving end tries to orgasm

Error log: 
[error.log](https://github.com/Innoxia/liliths-throne-public/files/6066109/error.log)
The above was produced with a centauress PC and a catboy PC imported into the game as a slave NPC. 

![image](https://user-images.githubusercontent.com/24850325/109595483-75e6b080-7ac9-11eb-802e-220952943bf1.png)
This image was produced in an opposite manner, with the catboy PC and the centauress being imported as a resident. With the orgasm button not working, going into the phone menu and back causes the button to disappear entirely.
It's worth noting that despite this two examples using the same characters, I've had this issue happen with other characters as well, such as a bunnygirl PC receiving anal from an enslaved Scarlett.

**Additional information:**
 - Game version 0.3.19
 - OS: Windows 10
 - Using .exe

**Comment by AceXP** [comment]
The cause is known, it happens when the character that is orgasming has a vagina (that is not being penetrated) and is penetrated in the ass while having at least a liking for the buttslut fetish. It should be fixed in the next release.

**Comment by MonsterButler** [comment]
Ah, good to know! Gotta love how that combination of factors just leads to the whole game breaking, but that's game dev for ya.

**Comment by AceXP** [comment]
This should be fixed in version 0.3.20, could you check it and close this issue?

`Fixed issue in sex scenes where background errors would be thrown and potentially softlock the game when an anal fetishist orgasmed while receiving anal and having an empty vagina.`

**Comment by MonsterButler** [comment]
Seems to be working fine now, thanks for reminding me.

**Comment by AngerySnek** [comment]
> The cause is known, it happens when the character that is orgasming has a vagina (that is not being penetrated) and is penetrated in the ass while having at least a liking for the buttslut fetish. It should be fixed in the next release.

Is this really fixed now? I get freezes and "crashes" like in OP's screenshot all the time on playing the latest release
