### ISSUE TITLE
(Mistaken) This issue can be deleted - I was wrong altogether.

### ISSUE THREAD

**Issue by dylithian** [Innoxia/liliths-throne-public#1519]
Steps to reproduce:
Become a demon in 0.3.19 (I have not tested this in 0.3.20).
Impregnate Lilaya
Proceed as normal.

Results:
Standard complaints about her pregnancy ensue. 
She states that she doesn't like getting pregnant because her children will be imps.
When she gives birth, imps wreck her lab.
The offspring tracker lists an appropriate number of imp offspring somewhere in Submission.

**Comment by dylithian** [comment]
Turns out using the debug menu causes impossible things.
What a shock!

...I'll show myself out.

**Comment by AceXP** [comment]
Go the Lyssieth route to become a demon. It will change the interactions with Lilaya.
