### ISSUE TITLE
No new enforcers spawn

### ISSUE THREAD

**Issue by Freimann01** [Innoxia/liliths-throne-public#1521]
As of version 0.3.20, new enforcers will never spawn in for the dominion enforcer encounter. If you load a save from a previous version where you've already encountered an enforcer squad, you will still encounter that squad, but new games will never get the enforcer encounter.

**Comment by AceXP** [comment]
This is a known bug that will be fixed in the next version.

**Comment by AceXP** [comment]
This is fixed in the 0.4.0 version, could you check it and close this issue?
