### ISSUE TITLE
Dragon offspring can't appear

### ISSUE THREAD

**Issue by FalconHalo** [Innoxia/liliths-throne-public#1522]
If the pc is a dragon-morph, and produces dragon-morph offspring, the children never spawn on any tile, as the species type doesn't seem to be assigned to any of the tile types on which offspring can appear. This happened when my pc sired offspring, and presumably, the same thing happens when they are the mother. 

My pc is a lesser dragon girl, and is the standard species as opposed to any of the subspecies (coatl, ryu, etc). Bree was the mother. 

Version 0.3.20
Windows 10 
Using .exe

**Comment by Stadler76** [comment]
Dragons aren't supposed to spawn in dominion which includes offspring. They are supposed to spawn in the world regions which are yet to be implemented. Consider Ralph selling dragon fruits as a sneak peek for what has yet to be added to the game.

Here's the snippet from `subspecies/dragon.xml` that defines their spawn locations:
```xml
<regionLocations>
	<region rarity="ZERO_EXTREMELY_RARE">VOLCANO</region>
	<region rarity="ZERO_EXTREMELY_RARE">DESERT</region>
	<region rarity="ZERO_EXTREMELY_RARE">MOUNTAINS</region>
</regionLocations>
```

**Comment by FalconHalo** [comment]
Got it, thanks for letting me know.
