### ISSUE TITLE
The Rogue ENforcer

### ISSUE THREAD

**Issue by Joao-Silva-Kuro** [Innoxia/liliths-throne-public#1527]
**Describe the bug**
Stuck on the end of the quest screen, after receiving the reward from Wes. This happened due to the time rolling over to past 17:00.

**Expected behavior**
I expected to receive the reward and be able to walk away or at least exist the dialog.

**To Reproduce**
Please include the steps that need to be taken in order to reproduce the bug.
e.g.:
1. Go to 'Enforcer HQ' while the quest 'Rogue Enforcer' is active and after delivering the recorded footage to Candi.
2. After a week has passed, enter the HQ roughly within 20 minutes of 17:00 and talk to Candi. Ask about Wes.
3. You will go through the dialog with Wes and receive the 'Wes's Contractor Pass' reward.
4. Because the dialog moves time enough to go past 17:00 you will be locked on that screen.

**Attach files**
![image](https://user-images.githubusercontent.com/34027777/113424786-44ab1a00-93c0-11eb-8c2b-51df445cad1e.png)
![image](https://user-images.githubusercontent.com/34027777/113424812-4ffe4580-93c0-11eb-82a4-7b5ea4dc8146.png)

**Additional information:**
 - Game version [e.g. 0.3.20]
 - OS: [e.g. Windows 10]
 - Using .exe

**Comment by Innoxia** [comment]
This will be fixed in the next update, thank you for the detailed report!
