### ISSUE TITLE
[0.3.20] Multiple Exceptions during sex with Fyrsia after defeating her 

### ISSUE THREAD

**Issue by RandomNecromancer** [Innoxia/liliths-throne-public#1535]
**Describe the bug**
During sex with fyrsia (after defeating her in battle for the Dark Siren quest), several buttons disappeared and the remaining ones stopped working. 

**Expected behavior**
To be able to have sex with Fyrsia normally after defeating her.

**To Reproduce**
Note: This problem happens occasionally and is not exclusive to this battle, but it happens more often in this situation than in others. After reloading and trying again, I was able to get past her sex scene normally. This bug sometimes happens when I do what is described below.

1. Start the Dark Siren quest
2. Go to Fyrsia's fortress
3. Defeat her in battle
4. Extensively transform her (Probably not related)
5. Start the sex scene and select a custom sex position (the purplish ones) under the Position tab
6. Set the imps as spectators, so that you are interacting only with Fyrsia
7. After some turns, change positions
8. Bug happens as described above

**Attach files**
[error.log](https://github.com/Innoxia/liliths-throne-public/files/6276220/error.log)

Note: Upon opening the game using "java -jar LilithsThrone_0_3_20.jar", I've also seen multiple unhandled "Exception in thread 'JavaFX Application Thread'" thrown in cmd.

**Additional information:**
 - Game version: 0.3.2.0
 - OS: Windows 10
 - Using .jar with java 1.8.0_271

**Comment by AceXP** [comment]
Known bug that is fixed in version 0.3.21 (and later).
