### ISSUE TITLE
Random encounters

### ISSUE THREAD

**Issue by Kon1399** [Innoxia/liliths-throne-public#1549]
Not exactly sure if it's a bug, but whenever I explore, with quicksaved game and I encounter an attacker, then load last save, and then explore, attacker is the same.
It wasn't the case in previous versions.

Ver. 4.0, exe.

**Comment by AceXP** [comment]
So far, I've not been able to reproduce this.

Steps I took:
-- quicksave the game, and walk in an alley tile
-- when there is an attacker, do a quickload and select explore
-- I've had attackers, prostitutes and Enforcers appear, the attackers were from different races (but not always) and with different fetishes.

So I'm not sure what is going on, if anything.

**Comment by Kon1399** [comment]
Be already at alley, when you quicksave, then explore. It must be first attacker right after save(if not, load). Check gender, race and fetishes. (load at least a few times to be sure)
My issue is that when you load and explore again, the following may happen:
 - finding an item
 - encountering enforcers 
 - encountering prostitute (possibly the same race and gender of attacker)
 - encountering an attacker. Check gender, race and fetishes. If encountered right after loading, attacker will be the same (gender, race, fetishes),
 However, after resolving those encounters, next attackers will change and act normal. That's why I was not sure if that's a bug. I'm mensioning that, because it did not happened in previous versions. That's my case at least.
