### ISSUE TITLE
Bat Girl Flame Demand Inconsistency

### ISSUE THREAD

**Issue by fgc1701** [Innoxia/liliths-throne-public#1557]
**Describe the bug**
Inconsistency with text and option for paying off assault in Bat Caverns, Bat Girl demands 250 flames but the 'Offer Money' option is 500 flames.

**To Reproduce**
1. Go to Bat Caverns
2. Be assaulted by a Bat Girl

**Attach files**

**Additional information:**
 0.4.0.6 Alpha
Windows 10
.jar 
Java Version 8 Update 291 (build 1.8.0_291-b10)

**Comment by fgc1701** [comment]
For clarity, the Bat Girl text specifically states:

'... So here I am, confronting you! And now you're going to have to pay me.​ Yes, that's right, pay me! **Two-hundred and fifty flames, to be exact!** So you pay me, or else I'm gonna make you pay! Funny how that works, huh? Anyway, what's it going to be? I tried to keep this brief, as I'm very busy right now, so I'd appreciate it if you could do the same.​ Just hand over your money, and that'll be that, ok?'

**Comment by AceXP** [comment]
Known issue that is taken care of by PR #1550 'Typos and consistency'.

**Comment by Innoxia** [comment]
This should be fixed in the latest version, thank you for the report!
