### ISSUE TITLE
Spinneret virginity can be lost only through quick sex

### ISSUE THREAD

**Issue by RandomNecromancer** [Innoxia/liliths-throne-public#1558]
**Describe the bug**
Spinneret virginity can be lost only through quick sex.

**Expected behavior**
To be able to lose spinneret virginity without the "Quick sex" action.

**To Reproduce**
1. Get a character with a virgin spinneret
2. Start sex and get your spinneret penetrated
3. Spinneret virginity won't be lost
4. Use the "Quick Sex" action while your spinneret is penetrated and your virginity will be lost

**Attach files**
No errors in the error.log

**Additional information:**
 - 0.4.0.8
 - Windows 10
 - .jar (java 1.8.0_271)

**Comment by AceXP** [comment]
The latest change includes a fix for this issue.
