### ISSUE TITLE
Spinneret depth isn't saved

### ISSUE THREAD

**Issue by RandomNecromancer** [Innoxia/liliths-throne-public#1562]
**Describe the bug**
Spinneret depth isn't saved properly. Each time the game is reopened and the save is reloaded spinneret depth is set to default.

**Expected behavior**
Spinneret depth to be saved and the intended value to be loaded upon reopening the game.

**To Reproduce**
1. Create a character with spinneret
2. Change spinneret depth to a non-default value
3. Save and exit the game
4. Open the game and load the save
5. Check spinneret depth

**Attach files**
No errors in the error.log

**Additional information:**
 - Game version: 0.4.0.10
 - OS: Windows 10
 - Using .jar with Java 1.8.0_271

**Comment by Innoxia** [comment]
I've got this fixed for the next update; thank you for the report!
