### ISSUE TITLE
[Bug] Pregnancy Stats are broken after 0.4.0.10 change to delete removed NPCs

### ISSUE THREAD

**Issue by TadUnlikely** [Innoxia/liliths-throne-public#1564]
**Describe the bug**
After the 0.4.0.10 change to delete removed NPCs after they are removed from the game, the pregnancy stats screen no longer shows anything about them.

If you impregnated a temporary NPC (through the brothel or during an arcane storm, for example), they are listed as "The Unknown Female (Woman)". I don't even have humans enabled.

If you are currently potentially pregnant, the only names it will show are those of permanent NPCs, and the name of your currently active partner, whether that partner has even inseminated you or not.

**Expected behavior**
The details that were formerly there should remain there. NPCs with active pregnancies should remain at least until the pregnancy resolves. NPCs who have inseminated you should remain until the resolution of that pregnancy.

**To Reproduce**
Please include the steps that need to be taken in order to reproduce the bug.
e.g.:
1. Go to the brothel
2. Engage in sex
3. Inseminate/be inseminated
4. Finish the scene
5. Check Pregnancy Stats
6. Confirm that the details for your partner are no longer there
7. If you were inseminated, have sex again and immediately check the pregnancy stats, and your current partner will be listed as a potential father.

**Additional information:**
 - Game version 0.4.0.10
 - OS: Linux
 - Using .jar or .exe: .jar
- If using .jar, and you are not including an error.log file/text, please include your java version: 1.8.0_251

**Comment by Innoxia** [comment]
This should be fixed in the next update, thank you for the report!
