### ISSUE TITLE
[Bug] Offspring being randomly assigned birth dates in 0.4.0.10

### ISSUE THREAD

**Issue by TadUnlikely** [Innoxia/liliths-throne-public#1565]
**Describe the bug**
**Christine Mason
She was born on the 15th January 1992, which, due to the fact that everyone in this world starts out as being 18 from the date of their birth, makes her fifty years old.​
She is your daughter.​ Christine likes you.​**

It's the 18th of January 2024. I suspect this is due to the change to delete removed NPCs.

**Expected behavior**
My offspring should maintain their birthdate, and not be older than me!

**To Reproduce**
Please include the steps that need to be taken in order to reproduce the bug.
e.g.:
1. Have kids
2. Find them
3. Check their birthdate.

**Additional information:**
 - Game version 0.4.0.10
 - OS: Linux
 - Using .jar or .exe: .jar
- If using .jar, and you are not including an error.log file/text, please include your java version: 1.8.0_251

**Comment by Innoxia** [comment]
This should be fixed in the next update, thank you for the report!
