### ISSUE TITLE
Meraxis' virginities restored on Elis

### ISSUE THREAD

**Issue by RandomNecromancer** [Innoxia/liliths-throne-public#1566]
**Describe the bug**
Meraxis had lost all her virginities during her demon transformation, but I was able to take her virginities again on Elis. 

**Expected behavior**
Meraxis to remain a non-virgin after losing her virginities during her demon transformation. 

**To Reproduce**
1. Turn Meraxis into a full demon (she should lose at least one of her virginities. All, in my case)
2. Advance on the main quest until you meet her again on Elis
3. Challenge her to duels until you can have sex with her
4. She will be a virgin again*

*I don't know if it was an intentional change, an oversight or an error caused by an old save, but I'm sure it really happened. 

**Attach files**
No errors in the error.log.

**Additional information:**
 - Game version: 0.4.0.10
 - OS: Windows 10
 - Using .jar with Java 1.8.0_271

**Comment by Innoxia** [comment]
Dis this happen after Meraxis was transformed into a demon in an older save, then you loaded into the new version and she'd regained her virginities? She has her body reset when loading in from a save older than 0.4.0.5, so that might be the cause.

**Comment by RandomNecromancer** [comment]
Sorry, I should have detailed my issue properly. It is as you say and I thought that you might had reseted her. I had some tests done on a new save yesterday and I couldn't reproduce the bug, but I wanted to make sure before updating the issue.

If it's okay for you, I'm gonna close the issue.

**Comment by Innoxia** [comment]
Thank you for the clarification!
