### ISSUE TITLE
[Bug] Scarlet's morning blowjob not ending

### ISSUE THREAD

**Issue by Toramizu** [Innoxia/liliths-throne-public#1586]
During Helena's Romance quest, during "Preparing for the Grand Opening", you have to spend the night at the boutique with Scarlet. She asks you to wake her up with a blowjob, but if you do, you can't end the sex event.
You can't use the "Quick sex" button because it's a scripted event, but no matter how many times she comes, she never ends it.

I think it is caused by the new "Dom AI won't end sex early", but it's been a while since I've done that quest.
On that note, a few scenes where the player can't gain lust (dislikes the acts or dick size too big) had to be resolved by "Quick sex", because the dom not stopping until player orgasm, even if it wasn't possible.

A solution would be a countdown after to dom orgasms before they give up, or stopping if the player's lust is too low.

Game version : 0.4.1.1 Alpha

**Comment by Innoxia** [comment]
This will be fixed in the next update, thank you for the report!
