### ISSUE TITLE
Blog/Github (browser launch) buttons hangs Lilith

### ISSUE THREAD

**Issue by picobyte** [Innoxia/liliths-throne-public#159]
The blog button in the far right in file menu (with save, load etc.) hangs Lilith for me. When clicked, no webpage is opened and the game does no longer respond, effectively hanging the game.
I think the reason may be that lilith has no permissions to start the browser in linux, that is no reason to hang though IMHO.

Platform arch linux x86_64, jdk1.8.0_161/bin/java
running lilith git, latest commit: e685d1d

This button is at src/com/lilithsthrone/game/dialogue/utils/OptionsDialogue.java 183

The same problem occurs when pressing the github button.

**Comment by picobyte** [comment]
Problem was also discussed here:

https://stackoverflow.com/questions/27879854/desktop-getdesktop-browse-hangs

**Comment by picobyte** [comment]
added pull request https://github.com/Innoxia/liliths-throne-public/pull/160 to fix this

**Comment by Innoxia** [comment]
Thank you for the report and fix! ^^
