### ISSUE TITLE
Massive Slowdowns and Inability to Save

### ISSUE THREAD

**Issue by PyxxisPine** [Innoxia/liliths-throne-public#1689]
So I've had this problem for quite a while, basically as far as I can remember playing the earliest builds of the game. Essentially, it seems, the longer I have the game open, the slower it becomes, until eventually there is a distinct lag when moving about the map or navigating through menus such as the shopkeepers. In some areas, such as the arcade, the game will become practically unresponsive, and I'll be unable to save and restart the game, which usually fixes the lag.

After looking through a few other bug reports, particularly #971, it seems the issue has been caused by the game running out of memory, as the log is absolutely filled with 

`java.lang.OutOfMemoryError: Java heap space`

I'm running the jar version (build 0_4_5), and my laptop has 8 gigs of RAM, of which the task manager says Java is only taking up 500 megs of. I'm currently in a freeze state with only 70% of my total RAM used, but the program is unresponsive to the point of the minimap not updating when I'm moving rooms (I found out you can force the game to do a location update by opening up the settings menu). 

I cannot regular save nor quicksave, and the last autosave was over an hour ago and I really don't want to lose my process. So, I gues sat this point I have a few questions:

1. Is anyone else having this problem?
2. Is there any way I can fix it?
3. Is there any way I can save my game in the program's current freeze state?

I'll include the error log, for what it's worth, and am happy to include any other information as needed.

Thanks!
Pyxxis
[error.log](https://github.com/Innoxia/liliths-throne-public/files/9392236/error.log)

**Comment by PyxxisPine** [comment]
I also forgot to mention:  In addition to slowdowns and the inability to save, I also cannot load new maps (I am currently stuck in the arcade).

**Comment by CognitiveMist** [comment]
500MB is quite small for this game, but we can ask Java to make this bigger.

First of all, ensure that you are using a 64-bit java, if you have a 64-bit system.

Second, to increase the memory allocation on the command line, you can add `-Xmx2G` to raise the limit to 2GB. If you are not using the command line or a batch file to launch the game, you might be able to add the argument using the 'Java Control Panel' that is installed with java, under 'Java' -> 'View' -> the 'Runtime Parameters' column.

**Comment by PyxxisPine** [comment]
Awesome. I already had it running 64 bit on 64 bit, but I allocated the extra ram in the control panel and it seems to have worked. I blitzed through everything I previously had done in the Arcade and was able to save with nary a slowdown. I'll give an update if I keep experiencing the slowdowns later, but for the moment this seems to have worked. Thanks!

**Comment by CognitiveMist** [comment]
Good to hear!!

Since your current problems are solved, it'd be good to close this issue. (Only the issue creator and Innoxia have permissions to do that)

**Comment by PyxxisPine** [comment]
Yep. After playing a few sessions, no more slowdowns. I'll shut the issue now.

**Comment by Eario** [comment]
I know this issue's closed, but is there a good way to do this fix with the exe version of the game? Can't figure it out myself.

**Comment by CognitiveMist** [comment]
@Eario 
Yes, there is a method.

Create a file called `LT.l4j.ini` alongside the exe. The first bit must match the name of the exe exactly. The second bit is L-four-J, not fourteen-J (some people had got that confused).

You may need to change Windows to show the file extension, if it isn't, to verify that the names are correct. 

Then, you can place command line options, one per line, within that file. E.g. `-Xmx2G`.

After that, simply launching the exe should use those options.

(If you have a discord account, you can get faster help on the LT discord if something isn't working as expected)
