### ISSUE TITLE
Selfie screen says I can fly, but the fly fast travel is unavailable

### ISSUE THREAD

**Issue by RandomNecromancer** [Innoxia/liliths-throne-public#1719]
**Describe the bug**
Selfie screen says I can fly, but the fly fast travel is unavailable.

**Expected behavior**
To be able to fly if I'm told so.

**To Reproduce**
1. Transform arms to bat and legs to serpent-tailed snake
2. Go to "Selfie" menu and see the "They are large and powerful enough to allow you to fly!" message
3. Go to "Maps" menu and the "Fly" fast travel option will be disabled

**Attach files**
[Bug.zip](https://github.com/Innoxia/liliths-throne-public/files/9764140/Bug.zip)

**Additional information:**
 - Game version: 0.4.6.3
 - OS: Windows 10
 - .jar 1.8.0_271
 - error.log empty

**Comment by whiskeyfur** [comment]
Not sure what is going on, but opening up your save game and checking out the 'transformation' options, I saw that you didn't have wings at all. And yet...
![image](https://github.com/Innoxia/liliths-throne-public/assets/3805521/bc90ad76-5a2a-4695-ae30-6566cc5f03ed)
![image](https://github.com/Innoxia/liliths-throne-public/assets/3805521/83c0bfa1-0834-4c98-b48b-8fcb6c181397)
That is strange!

**Comment by whiskeyfur** [comment]
Have you actually applied any transformation potions to give you wings or was it like this from the start?

**Comment by RandomNecromancer** [comment]
@whiskeyfur srl, I completely forgot about this issue.

You got it wrong. They are bat arm-wings.

**Comment by whiskeyfur** [comment]
Truth be told I had forgotten about this as well. I was just asking for some clarifying information, is all.

**Comment by RandomNecromancer** [comment]
Fixed on 0.4.9.9
