### ISSUE TITLE
Mods Causing Game To Not Function

### ISSUE THREAD

**Issue by RandyMandy** [Innoxia/liliths-throne-public#1728]
I'm not sure if you can fix this, or if it's just my pc, but anymore than two mods will cause mass amounts of lag and freezing, and causing all buttons to freeze and not work. 

And even with two mods, it does have minor lag, and I often have to double click on most buttons because they wont work otherwise.

I'm sorry if this problem is already on here or if it's just my pc. Thanks.

**Comment by RandyMandy** [comment]
I just realised that there was a template for issues, i'm sorry for my idiocy in not realising that. feel free to close it for that reason if need be.

**Comment by CognitiveMist** [comment]
Hey, if the issue comes back, feel free to drop into the game's discord channel (linked from the blogspot page) and ask in the #mod-discussion or #tech-support channels there, mods causing lag is a common issue, and some types of mods are worse than others.
