### ISSUE TITLE
game doesn't work. like at all. opens but is not functional.

### ISSUE THREAD

**Issue by Moth-GITHUB** [Innoxia/liliths-throne-public#1750]
**Describe the bug**
Main start menu doesn't work. none of the buttons work. 
I downloaded the game again and it worked but after closing the game and starting again then none of the buttons worked again

**Expected behavior**
the buttons work

**To Reproduce**
Please include the steps that need to be taken in order to reproduce the bug.
1.download game from blogspot (.exe, mega)
2.extract
3.open application
4.press new game then go back to main menu (was checking what the other starting skills are so not making a new character)
5.close application
6.open application again
7.bug (try clicking on like new game or options or sum)

**Attach files**
Game Version: 0.4.7
Java: 1.8.0_172 (Oracle Corporation)
OS: Windows 10 (amd64)
Mod folders present: innoxia

**Additional information:**
 - Game version [0.4.7]
 - OS: [Windows 10]
 - Using .exe

**Comment by Moth-GITHUB** [comment]
Might aswell mention that the previous download of game wasn't working/doing the same so that's why I redownloaded game to check if maybe my download somehow got fucked up (pardon the language)

**Comment by CognitiveMist** [comment]
Did anything appear in `data/error.log`?

**Comment by Moth-GITHUB** [comment]
redownloaded game to check if I missed something. as there is only error.txt. what I have put in "attach files" is what was inside of the error.txt

so to answer your question. I'm not sure. but I say this again I REDOWNLOADED the game and now it works. not sure how or why? I haven't done anything with my system. haven't even restarted it or closed any application. I just deleted LT then redownloaded it for like the 3rd time or something and now the bug is gone.
which mean's it's not gone because no changes were made but the bug has been bugged somehow

**Comment by Moth-GITHUB** [comment]
all I did was accidentaly go too far into prologue to the point I couldn't go back and change things and that apparently fixed it
