### ISSUE TITLE
I don't know if this is a bug or not but...

### ISSUE THREAD

**Issue by JammyNJelly** [Innoxia/liliths-throne-public#1826]
Lilaya doesn't have the option to go full demon even though I am one (I think, I have a poor memory) please fix this I really like this part of the game. And just in case I'm not a full demon, could you tell me how to get it?
I have just came back to Lilith's Throne after a LONG break so it could just be removed and I don't know.

**Additional information:**
 - Game version [e.g. 0.4.9.9]
 - Using .exe

**Comment by CognitiveMist** [comment]
Do you remember what version (or even approximately what date) you last played? It's not impossible that the scripts for updating saves from older versions has a bug.

Could you upload your save? I think I could check it to see if it is a bug, or otherwise what step in the process you're missing.

**Comment by JammyNJelly** [comment]
@CognitiveMist I started a new save so don't think it's a script issue. 
And it seems like GitHub doesn't support the type of file my saves are, sorry.
