### ISSUE TITLE
(0.2.0.5) Time not passing in submission

### ISSUE THREAD

**Issue by SterlingVoyager** [Innoxia/liliths-throne-public#194]
As the title says, no amount of walking in submission or exploring its tunnels passes time in either of my main save files. Only entering or leaving Submission passes time, and even that is inconsistent. Traveling out of Submission takes 11 minutes while traveling into Submission takes six. (Admittedly, this might make sense if stairs are being taken. It also might be that 5 minutes are passing from moving in between Dominion tiles.

**Comment by Innoxia** [comment]
This has been fixed in 0.2.1. Thank you for the report! :3
