### ISSUE TITLE
Slavery UI bug

### ISSUE THREAD

**Issue by Innoxia** [Innoxia/liliths-throne-public#198]
When navigating the slave menu, if you're in slave A's room and you try to look at slave B's profile, the right sidebar will show slave A's stats, regardless of checking slave B, C, D, etc. Opening the intended slave's inventory properly shows the correct slave's stats in the sidebar.

**Comment by pokerface17** [comment]
is arthur the same way as this bug?
step:
reunite arthur back to liliya
go to any room.
select whichever the room except the room you currently in.
put arthur in the room.
may this help

**Comment by Innoxia** [comment]
This has been fixed. (Tested in 0.2.6.2)
