### ISSUE TITLE
Character creation bug

### ISSUE THREAD

**Issue by Innoxia** [Innoxia/liliths-throne-public#204]
When you attempt to start up a new game while playing an existing game, if you choose a female character is doesn't want to let you pick the androgynous option. If you want your character to be a tomboy from the start, the game won't let you without closing out of the game and restarting.

**Comment by bicobus** [comment]
Issue related to femininity and gender: if you pick a male start then an androgynous femininity, you can't grow a beard. It seems that the femininity trumps biology.

**Comment by Innoxia** [comment]
Fixed by Master of Puppets.
