### ISSUE TITLE
Bug: Active Traits

### ISSUE THREAD

**Issue by Candycanes** [Innoxia/liliths-throne-public#214]
Active Trait perks are giving their bonus/negative stats even when not equipped to the active bar.
After taking Nymphomaniac my Seduction Resist decreases by -25 permanently but only got the bonus 2 essences per orgasm whilst it was equipped.
This is the same with all Active perks that give bonus stats. (Brawler, Observant, Runner, Cardio Queen, Nymphomaniac, Arcane Precision, Arcane Combatant, Resilient Aura, Indomitiable Aura)

(Minx and Ladykiller appear to be working only when equipped and perk effects like Nymphomaniac bonus essence and Arcane Combatants debuff only proc whilst active)

**Comment by Pimvgd** [comment]
Cannot reproduce in 0.2.6.2
