### ISSUE TITLE
Minor Request: Additional Human Skin Colours

### ISSUE THREAD

**Issue by Candycanes** [Innoxia/liliths-throne-public#219]
Colour Name	RGB Colour Code
	Rosy		#DDA993
	Porcelain	#DBCDB9
	Tan		#C39D6B	
	Fake Tan	#B67D38
	Chocolate	#59372D

Could rename 'Fake Tan' as 'Dark Tan'.

**Comment by colin18swood** [comment]
Something else that might be related to this, is if tan-lines could be added in some capacity.  You could have your main skin tone, and then you could select a second skin tone for the tan-lines.  You could also possibly have several types to choose from.  For an example, checkout the game Kisekae2 by Enty (A dress-up game).  The sixth or seventh tab over has 15 different tan-lines for different types of swim- suits/underwear.  Here's a link: http://pochi.x.fc2.com/kisekae/k_kisekae2.html
