### ISSUE TITLE
Sex Action arousal increases need looking at

### ISSUE THREAD

**Issue by Innoxia** [Innoxia/liliths-throne-public#221]
Some actions shouldn't affect arousal? #193

**Comment by A-Master-of-Puppets** [comment]
There are literally only five actions that decrease arousal in the game:
- Pix denying the player
- The player calming down
- The player denying an NPC
- The two general "Resist" actions
All the actions to resist a specific action, like "Resist Oral", and also the "Beg for [himHer] to stop" dirty talk variant, these all have _positive_ arousal.
I would suggest that the "Resisting" actions should probably cause zero arousal, with the exception of ones that involve stimulation such as being fucked or licked/blown against their will.
Also, restrict the player from using "Calm Down" if they are being raped; being able to slow down and take a breather should require some measure of control of the scene.
That would fix the problem where it is very difficult to make an NPC cum against their will, and they simply can't do it _at all_ to the player.

**Comment by Innoxia** [comment]
I've fixed this for 0.2.3.5. :3
