### ISSUE TITLE
XP gains need balancing

### ISSUE THREAD

**Issue by Innoxia** [Innoxia/liliths-throne-public#237]
"XP seems off. I'm leveling up after every single combat on both new and old characters. It's kind of fun but I imagine it is not supposed to happen.

On further experimentation, it seems this occurs on any non-human difficulty. Playing on Morph or higher results in every combat giving you (level*10) amount of xp, which means an automatic level up."

There have also been several reports of high XP gains in Submission. This needs balancing.

**Comment by bicobus** [comment]
High XP gain for weak NPC encounters. Why does NPC attacks people without weapons? Hell a simple steel bar would do the trick. Passed a certain level, the player becomes immune to any kind of physical damage. This could be alleviated in the current releases by putting a cap on the player's level, and progressively increasing that ceiling as you release content.

**Comment by Rfpnj** [comment]
We made adjustments to the XP system with PR #288
