### ISSUE TITLE
Breastfeeding continuous action

### ISSUE THREAD

**Issue by Innoxia** [Innoxia/liliths-throne-public#239]
Make breastfeeding like kissing, in that it's a continuous action.

**Comment by TadUnlikely** [comment]
@Innoxia Completed in 0.3.5.4, confirmed still working in 0.3.6.8.

**Comment by Eliria** [comment]
Breastfeeding continuous action is not currently available for crotch breasts.

**Comment by Innoxia** [comment]
I've added continuous breastfeeding actions to crotch-boobs/udders for v0.3.8 (which will be out in a day or two), so I'll close this now.
