### ISSUE TITLE
Unable to run the game @c4e04d0

### ISSUE THREAD

**Issue by Zj-Ax** [Innoxia/liliths-throne-public#24]
I tried to lunch the game in Eclispe, and i'm unable to lunch it at commit c4e04d028b7edaa96cbc358fc70ee5875b714f28

I didn't modified yet, I lunched fresh from a git pull.  

The errors : 

> Exception in thread "JavaFX Application Thread" Exception in thread "main" java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
> Caused by: java.lang.NullPointerException
> 	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:383)
> 	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
> 	... 5 more
> java.lang.ExceptionInInitializerError
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Unknown Source)
> 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplicationWithArgs$156(LauncherImpl.java:352)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
> 	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
> 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
> 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> 	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
> 	at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.NullPointerException
> 	at com.base.main.Main.<clinit>(Main.java:73)
> 	... 11 more

**Comment by Rfpnj** [comment]
There is a bug that will be resolved at the next commit by Innoxia, There is an error in the colour.Java file where there is two extra ) down in AllMetals.

**Comment by Zj-Ax** [comment]
Resolved @4b115139638cac69171f8c58144aa4ba67df6f74
