### ISSUE TITLE
Character stats loading bug

### ISSUE THREAD

**Issue by Innoxia** [Innoxia/liliths-throne-public#240]
When using a character that has been created in version 0.1.98 (doesn't matter if it has been saved in, say, 0.2.0, then used again in this build, just the creation time counts) or older in any of the new builds that have the reworked stat system, then the player—and only the player—has a permanent malus of 2 physique, 5 physical resistance, 5 seduction resistance and 5 physical damage.
Easily reproducible by creating a new character in 0.1.98 (the oldest build I still have at hand), make them virgin, strip them naked, save, then drag that save to 0.2.1.1. The stats will look like this in the sheet:

13 physique (10 base / 3 bonus, should be 5)
0 physical damage (0 base / -5 bonus, should be 0)
0 physical resistance (0 base / -5 bonus, should be 0)
40 seduction resistance (0 base / 40 bonus, should be 45 (20 from human, 25 from minimum corruption))

Doesn't matter if you export that character and start a new game with it or just drag over the save. Exporting the character and using them as a slave will get rid of the malus though. No NPCs seem to be affected.
I tried looking at the save file over and over but can't find anything, the malus seems invisible, as changing your stats in the .xml still applies it ingame. No undisplayed status effect, deleting your fetishes does nothing, your inventory doesn't matter, nor does your race, and characters created after the stat rework work just fine. I'm stumped here.

---

All right, it includes characters created in 0.2.0.2 as well, with the exact same malus. Characters created in that version had 2 more physique and arcane than they should have, I now notice. But still, the stats look the same as above when imported from that version.

---

And it looks like that bug was present for all characters, even newly created ones, in version 0.2.0.5. Still the same malus as mentioned above.

**Comment by Pimvgd** [comment]
Fixed in #693.
