### ISSUE TITLE
.com.lilithsthrone.main.Main folder created in home directory causing issues with resources folder

### ISSUE THREAD

**Issue by Tandemmirror** [Innoxia/liliths-throne-public#245]
OS: Linux Mint 18.2
Java Version: 1.8.0_161

Okay, I'm _really_ not familiar enough with Java to tell you what exactly is going on here, but I'll tell the story from start to finish and you can see if I missed anything:

Ever since the version that added the "res" folder I've been getting the issue where the text stored in that folder won't load up in the main game. I verified that the res folder was indeed in the same directory as the jar, and then verified the integrity of the res folder itself, so neither of those were the source of the issue.

I noticed that when I launch the jar a folder is created in my home directory called ".com.lilithsthrone.main.Main". It only contains blank documents and empty folders, and I can delete it without losing my saves. The moment I run the jar again, the folder is recreated in the exact same way. I understand that the word "main" means that it's probably important, so I copy the "res" folder for the latest version into my home directory, to see if the missing text suddenly works, and that's what solved my issue. But I get the feeling that the game was misbehaving when it interacted with my OS to have that problem in the first place.

Is this bug specific only to me? Now that I know the fix, it wouldn't bother me to work around it, but I don't know if it's indicative of some greater error.

Thanks for listening!

**Comment by A-Master-of-Puppets** [comment]
How are you running the game? The res folder doesn't need to be in the same folder as the jar, it needs to be in the _working directory_ that you run the game _from._ For example, if I run `java -jar LilithsThrone/LilithsThrone.jar` from my home folder, then the res folder needs to be at `~/res`, *not* `~/LilithsThrone/res`. The same goes for the data folder.

**Comment by Tandemmirror** [comment]
That might be it, actually. I run it by double-clicking on the icon :p. That must run it with respect to my home directory, which is why the data folder is created there. And when I run it in terminal from the directory its located in, a brand new data folder is created in the proper place, and the res folder also loads correctly.

Thanks for pointing that out! I probably wouldn't have caught on to that if you hadn't mentioned it. Making a simple shell script to execute the jar from the directory its in allows me to run on click without worrying about the working directory being the home folder. It turns out this was causing other issues (all of the versions sharing a cumulative data folder turned out to have bad consequences, even if made importing and exporting saves easier) so I'm glad to have a solution.

**Comment by A-Master-of-Puppets** [comment]
Hmm, what bad consequences do you get from using the same data folder across versions? That's the way I run it, and I haven't noticed anything.

**Comment by Tandemmirror** [comment]
Ah, shared save files. The game doesn't change enough that loading up an old version's save file usually breaks things, but it causes certain problems (I have a character from version 1.95 with clothing with the old lactation enchantments, for example, which still function in 2.11 - this is something that is true even with character imports across versions - as well as the fact that old save files have old maps in them). It's not a huge deal, but I feel like the greater the distance between versions becomes, the more minor changes like this will add up. I'm smart enough to know I should start a new game for each public release (even if I'm just importing the character) but I'm not sure everyone will be, and if you're not deleting old saves it might be harder to keep track.

**Comment by A-Master-of-Puppets** [comment]
If there are problems with saves from older versions, you should open an issue for that; they're supposed to work just fine. Some of the saves I have started in 1.89, and the most serious problems I've had is potions disappearing and clothing losing it's enchantments; hardly game-breaking issues.

**Comment by Tandemmirror** [comment]
Alrighty then. I consider my main issue with this resolved, more or less, and it seems to have been caused by a quirk of my operating system, so this is okay. I'll try and keep an eye out for bugs with persistent saves while I'm playing. Thanks.
