### ISSUE TITLE
Unable to receive oral sex in the public stocks

### ISSUE THREAD

**Issue by junglejain** [Innoxia/liliths-throne-public#260]
This is kind of strange, but I believe that the *slave* must be allowing vaginal use in order for a PC with only a vagina to receive oral sex.

Reproduce:
PC with only a vagina
NPC not allowing vaginal use (or with no vagina)
Choose Position -> Move to Front
No Sex actions available.

**Comment by Innoxia** [comment]
Will be fixed in 0.2.3.5. Thank you for the report!
