### ISSUE TITLE
Error logging commented out?

### ISSUE THREAD

**Issue by A-Master-of-Puppets** [Innoxia/liliths-throne-public#264]
Did you mean to disable error logging? I can't tell if it was deliberate or a mistake, since the commit is almost a thousand lines long, and just called "0.2.1.5 multiple bug fixes".

**Comment by Innoxia** [comment]
Yeah, that's deliberate while I'm working on it - I find it a lot easier to get error logging in the console than written to a file.

I'll uncomment it before exporting as a .jar. ^^

**Comment by A-Master-of-Puppets** [comment]
That makes sense, but that kind of thing probably shouldn't be committed to git; just keep that in the working version.

**Comment by Innoxia** [comment]
Good point ;_;
