### ISSUE TITLE
Offspring race bug

### ISSUE THREAD

**Issue by Innoxia** [Innoxia/liliths-throne-public#266]
Blog report:

"Major Bug in Hotfix version: PCs AND NPCs can only give birth to humans regardless of their race or their father's race, even though the birthing scene refers to them as their intended race. This means even demons/imps will only give birth to humans as well. Offspring of slimes, however, will still be slimes, but they can only be *human* slimes."

**Comment by AlacoGit** [comment]
Has this been fixed or is it still an issue? demons make imps just fine in 0.2.1.5

**Comment by Innoxia** [comment]
I'm not sure... I was unable to reproduce this bug when I went to fix it yesterday. I'll try again this evening and see if I can find out what could be going wrong.

**Comment by AlacoGit** [comment]
Might be something with Human male PC fathers and female non-demon mothers

**Comment by Innoxia** [comment]
The person who reported it:

"You can close that major bug in github about pregnancies not working with correct race as it's tied to bad properties files from older versions."
