### ISSUE TITLE
[0.2.2] INVALID_TARGET_NAME when asking Angel about prostitution

### ISSUE THREAD

**Issue by bicobus** [Innoxia/liliths-throne-public#309]
> INVALID_TARGET_NAME	Angel replies, sitting back in her chair as she lowers her pen, "prostitutes can work in any part of the city, so long as they have a license.	Brothels, however, are only allowed to operate in the red-light district, so all of the prostitutes that you see out in the rest of Dominion are working out of their homes."

In angel's kiss office, when talking to angel about prostitution.

**Comment by Innoxia** [comment]
Fixed, thank you for the report! :3
