### ISSUE TITLE
Dream lovers-keep quiet- double pharase.

### ISSUE THREAD

**Issue by DenizenScorpio** [Innoxia/liliths-throne-public#311]
"As you make your way around the store for a second time, you discover a very well-hidden corner full of sex toys, which you happened to miss before.	You wonder why Ashley would hide these items away.	After all, given the sexually-charged nature of Dominion, you're sure that these items would sell extremely well if they were a little more visible.	You decide that you'll have to ask Ashley about this some other time; after all, they're not exactly receptive to questioning."
Is displayed twice.

**Comment by Pimvgd** [comment]
This was fixed in dcfe12bfab92b18b70c19cdf91d578862c873bc9
