### ISSUE TITLE
Egg-Layer Player Characters using Livebirth Scene

### ISSUE THREAD

**Issue by Ettanin1987** [Innoxia/liliths-throne-public#312]
https://github.com/Innoxia/liliths-throne-public/blob/cc253afa1bee75d086f90a2bae8bf6de98be7c21/src/com/lilithsthrone/game/dialogue/places/dominion/lilayashome/Lab.java#L2503-L2526

Egg-Layer PCs like Alligator-Morps shouldn't use livebirth scene, but instead use an egg-laying scene. The current implementation only covers Harpies. This is killing immersion. A workaround would be using the harpy-specific scene in the meantime as it seems generic enough.

**Comment by Innoxia** [comment]
Added for v0.3.5.5. Sorry it took so long!
