### ISSUE TITLE
Dominion Boulevard flagged as dangerous in storms

### ISSUE THREAD

**Issue by A-Master-of-Puppets** [Innoxia/liliths-throne-public#314]
Is Dominion Boulevard, Lilith's Plaza, Demon Home, etc. supposed to be dangerous during arcane storms? The text says that demon enforcers patrol these stopping anyone from attacking you, and walking around extensively, I haven't been attacked. It seems like given this, they shouldn't be flagged as dangerous places even during storms.

**Comment by Innoxia** [comment]
I've got this fixed for the next update. Thank you for the report!
