### ISSUE TITLE
Harpy quest conflict with main quest

### ISSUE THREAD

**Issue by adfgagare** [Innoxia/liliths-throne-public#337]
When you complete the part of the main quest involving alexa the harpy matriarch and scarlette the andro harpy slave trader, in the event of not taking the punishment when alexa takes over the slave shop you cannot complete the calm the matriarchs quest.

**Comment by A-Master-of-Puppets** [comment]
Why can't you complete the harpy quest? Alexa doesn't have anything to do with that quest.

**Comment by adfgagare** [comment]
Ah sorry about that, i went to check after your message and found the fourth nest, i assumed alexa was the matriarch
