### ISSUE TITLE
Bug: Lilaya immediately backs out of Geisha submissive sex

### ISSUE THREAD

**Issue by TadUnlikely** [Innoxia/liliths-throne-public#360]
Commit 7f723ab introduced better detection of the incest fetish, but had the unintended consequence of making Lilaya immediately back out of Geisha submissive sex. This makes it very difficult to, for example, lose all your virginities to Lilaya.

**Comment by TadUnlikely** [comment]
Pull request #359 corrects this.

**Comment by Innoxia** [comment]
I merged #359, so this should now be fixed. Thank you for the report and fix! :3
