### ISSUE TITLE
Enchantment issues

### ISSUE THREAD

**Issue by soleil343** [Innoxia/liliths-throne-public#365]
[error.log](https://github.com/Innoxia/liliths-throne-public/files/1929795/error.log)
possible issue with enchantment, causes game crash on rest till morning/evening

Steps to reproduce

1: new game (log used female character)
2: progress to enchantment access 
3: enchant clothing (example uses maid gloves for wetness effect on breast)
4: use room to rest till morning/evening, no text related to enchantment will display, crash

**Comment by Pimvgd** [comment]
Recursive UtilText.parse is fixed by #482, thus this can no longer occur
