### ISSUE TITLE
Personality values not importing.

### ISSUE THREAD

**Issue by Git-Gud420** [Innoxia/liliths-throne-public#372]
They export fine, but upon importing all the values become average.

**Comment by TadUnlikely** [comment]
Can confirm on 0.2.3.5.

**Comment by TadUnlikely** [comment]
@Innoxia: I found the problem - the save routine isn't writing the personality entries correctly. I have a fix on my personalitySaveFix branch, but I'll need a little bit of time to write a recovery routine for the existing values. I should have it ready within the next hour or so.

**Comment by Innoxia** [comment]
Thank you for the report and fix! This is fixed in 0.2.4. ^^
