### ISSUE TITLE
Issues with Java

### ISSUE THREAD

**Issue by Yankigal12** [Innoxia/liliths-throne-public#374]
Just found game and love it!!  I play on a Mac and the latest version of Java for the Mac OS is version 8.  I have issues with the game crashing every 5 to 10 minutes.  I'm sure this is a compatibility issue with Java and Mac and wondered if you considered parsing a version for Mac users and Windows users?  Since most windows users are likely on Java 10, the Mac version may just be the version built for the Java 8 platform.  Thanks and keep up the great work.

**Comment by Garnetxx** [comment]
What version of mac os do you have? You'll need Java 9 or later [Java 10 JRE downloadable on here](http://www.oracle.com/technetwork/java/javase/downloads/index.html)
[Java 9 has reached the end of support?](http://www.oracle.com/technetwork/java/javase/downloads/jre9-downloads-3848532.html)
I'm running it fine on osx 10.9.5 with Java 9.0.4

**Comment by TadUnlikely** [comment]
Java 8 still has frequent updates coming out for it. I've been running LT under Java 8 (currently on 8u162) for months now, and it works fine for me. Building it is a little tougher, but it works fine as well.

**Comment by Yankigal12** [comment]
Thank you both; I will try to download the Java 10.  I did find it but was not sure how to go about the installation process.  I'm assuming I just dump it into applications and it should be ok.  Will leave an update.

**Comment by Yankigal12** [comment]
Sorry hit the wrong button; I'm running OS 10.13.4 on my mac.

**Comment by Yankigal12** [comment]
Garnetxx thank you very much for the link.  I downloaded Java 9 and so far so good.  Have had a long run without any crashes.  Thanks again!
