### ISSUE TITLE
Item encyclopedia misaligned

### ISSUE THREAD

**Issue by BluefoxKitsune** [Innoxia/liliths-throne-public#376]
Having the "Spellbook: Telepathic Communication" unlocked throws the rest of the encyclopedia out of alignment, presumably because the title is 2 lines and the body is only 1

**Comment by Pimvgd** [comment]
![lt376](https://user-images.githubusercontent.com/20502925/40936274-224dedc4-683b-11e8-8a48-d857f5dba8e2.PNG)

Cannot reproduce
