### ISSUE TITLE
Milking Room upgrades cannot be built if you have companions

### ISSUE THREAD

**Issue by LeechingLecher** [Innoxia/liliths-throne-public#378]
The Milking Room upgrade option is red and the button is greyed out if you have an elemental and companion (not sure, didn't test extensively) with you. Potentially also with just one of them, didn't test extensively. 

Dispelling the elemental and sending the companion away re-enables the option to purchase the room upgrade.

**Comment by AceXP** [comment]
This one is still open as well, time to close it I think.

When you are logged in, there is a link to your Issues at the top bar. I think there is one more from you.

**Comment by LeechingLecher** [comment]
No companions now anyway.
