### ISSUE TITLE
Several management buttons for a slave become unavailable after sending them to the stocks

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#398]
**Version** : 0.2.4.0
**From** : Discord
**Date** : 1 May 2018

"Does sending a slave to the public stocks bug them? I sent one on extended shift and even when they are in room can't manage their job/permissions/or interact with them. I guess the only things I can add to it Nnxx is slave was pregnant when set to the extended night shift and on a promiscuity pill but then changed"

(Bugged save attached)

[Rykith.zip](https://github.com/Innoxia/liliths-throne-public/files/1965190/Rykith.zip)

**Comment by Innoxia** [comment]
Thank you for the report! This was caused by some references to a "NOT_SET" character, which I've caught and handled properly. This save will work for 0.2.5, so I'll mark this as fixed. ^^
