### ISSUE TITLE
Scarlett's upkeep cost is oddly high once you get her

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#415]
**Version** : 0.2.4.0
**From** : Discord
**Date** : 1 May 2018

"is anyone else getting an upkeep charge even if they don't have any slaves/rooms?
I started a new character and after getting Scarlett I discovered that my balance is -20k even though I haven't done anything
and my upkeep is 4150 a day

**Possible cause** : "did you start that game after having another game loaded? The upkeep is checked when rooms are altered, and only then as far as I can tell. What's happening is that the game keeps the upkeep from the game that HAS the slaves, and doesn't recheck the slave upkeep when a new game is started. Or loaded.

Same bug lets you start a new game off a freshly opened LT, then load a late game save, and as long as you don't change any of your slave rooms you will have an upkeep of 0 flames."

[Hunk-upkeepbug1.zip](https://github.com/Innoxia/liliths-throne-public/files/1965300/Hunk-upkeepbug1.zip)
"

**Comment by Pimvgd** [comment]
Fixed by #695.
