### ISSUE TITLE
Roles are reversed during non-consensual shower sex with Pix

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#424]
**Version** : 0.2.4.5
**From** : Discord
**Date** : 3 May 2018

![screenshot_77](https://user-images.githubusercontent.com/23719598/39567482-6a98b0cc-4ebf-11e8-8d6d-f3a5ef8aff02.png)

=> It says the PC is the one pinning and Pix is the one facing the wall while it should be the contrary

**Comment by stealthcomment** [comment]
This appears to have been fixed in 0.2.8.5 https://github.com/Innoxia/liliths-throne-public/commit/032a4bd279494cdb932c2f097f679fef07cfa2b4#diff-6600e7fc1834dd90195aea18adec9150
