### ISSUE TITLE
Some appearances attributes aren't saved properly and are randomized upon loading

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#431]
**Version** : 0.2.4.5
**From** : Blogspot
**Date** : 3 May 2018

"Good to see the save file size being reduced, that really helps a lot. But it seems some things relating to appearance now don't get saved. So far I found lip-, nipple-, anal rim- and pubic hair colour. They get randomised on every reload.
Sclera-, pupil-, makeup-, all internal wall- and tongue colours get reset.
Happens to both you and every NPC."

**Comment by WoefulWombat** [comment]
Short update on this for **0.2.5**:

Colours of armpit-, ass- and pubic hair as well as lips, anal rim, and nipples and aren't saved for anyone and randomised instead on every reload. _Lips, nipples and anal rim now always share the same colour._

Sclerae, pupils, tongue, internal walls _(save for vagina, that now gets saved)_ and makeup reset to their previous state on reload after changing them through transformations or Kate.

**Comment by WoefulWombat** [comment]
Update for **0.2.5.1**:

Mostly fixed now, only makeup and pupil colour continue to not be saved (sclera does get saved).

**Comment by Innoxia** [comment]
Thank you for the details! This should be fixed in 0.2.7. :3
