### ISSUE TITLE
Removing NPC from back alley after a fight do not work anymore.

### ISSUE THREAD

**Issue by bicobus** [Innoxia/liliths-throne-public#435]
Version: 0.2.4.5
Log: [error.log](https://github.com/Innoxia/liliths-throne-public/files/1972961/error.log)

Behavior: clicking *remove character* after a fight will trigger a `java.lang.NoSuchMethodError`.

**Comment by huntexD** [comment]
Was a build error, go ahead and close

**Comment by bicobus** [comment]
Solved after removing the target folder and a git pull.
