### ISSUE TITLE
You can use dye markers for an unlimited amount of time after buying 10 of them

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#439]
**Version** : 0.2.4.5
**From** : Fenoxo's forum
**Date** : 5 May 2018

"Buy ten dye markers and you can dye everything and not lose any. Go over and still don't lose dye pens. Sold down to five and bug persisted. Seems to be triggered by 10 markers."

**Comment by Pimvgd** [comment]
Cannot reproduce on ad09d08835661cc5c983016a31025e52f79e4652 (0.2.4.5); see attached reproduction savefile
[infinite dye marker issue 439.zip](https://github.com/Innoxia/liliths-throne-public/files/1977508/infinite.dye.marker.issue.439.zip)

**Comment by Pimvgd** [comment]
Also tried reproducing on db89b7be26e9de89c70038b71eeb5a3e4e6c10a5 (0.2.4), still could not reproduce; see attached reproduction savefile
[v024 infinite dyemarker i439.zip](https://github.com/Innoxia/liliths-throne-public/files/1977521/v024.infinite.dyemarker.i439.zip)
