### ISSUE TITLE
Walking into a milking room shows the correct management UI, but the PC stays out of the room on the map

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#457]
**Version** : 0.2.5
**From** : Discord
**Date** : 10 May 2018

*I'm experiencing a strange bug- the map doesn't actually show me as being in the milker room despite the UI showing I am. And on top of that, the bottom bar's buttons do nothing, although I can sell and drink milk.*

![bug](https://user-images.githubusercontent.com/23719598/39879516-4d15a3a4-547b-11e8-90f2-487a5631c37e.png)

*I have two milking rooms, and both seem to experience this bug.
However, creating a new milking room on the second floor does not experience this bug. It is also empty, so I will test and see if it's due to lingering effects of having slaves in my old milking rooms, having milking rooms on the second floor, or having milking rooms filled with slaves.
Okay, it isn't just that the new one is on the second floor. Now I will test and see if it's because slaves are inside it, and whether or not emptying them of slaves does or does not actually fix the issue.
Okay, so no, it is not solely the result of slaves. It seems that milking rooms created prior to the latest patch are bugged like this.
Resetting the rooms and then remaking the milking rooms seems to fix it.*

*Okay, I was wrong- the bug reappeared. It goes away temporarily if you remake the milker rooms, but goes back once you leave it alone and let your slaves use it.
And even when your slaves leave that room, it still happens.*

**Comment by Innoxia** [comment]
Fixed (hopefully the only) cause of this for 0.2.8. :3
