### ISSUE TITLE
An abnormal amount of NPCs seems to have retained their penile virginities

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#464]
**Version** : 0.2.5
**From** : Discord
**Date** : 11 May 2018

"Every character seems to have their penile virginity when I've got genders like futa, etc encounters active. They lose the virginity just fine, but it seems odd that even the succubi encounters have penile virginity intact."

**Comment by Innoxia** [comment]
NPCs have an 85% chance to spawn in having already lost their penile virginity. This was only being applied to NPCs who spawn in with a penis, however, so if you got a demon or imp to grow a penis, it would always be virginal. I've changed this so demons and imps are always subject to the 85% loss chance, even if they spawn in without a penis (as they should be assumed to have grow and used one in the past).
