### ISSUE TITLE
Suggestions: MOAR BDSM!

### ISSUE THREAD

**Issue by ThatWhichLurks** [Innoxia/liliths-throne-public#491]
A few random ideas regarding bondage, dominance/submission, and sadism/masochism, including one that would be delayed until PC slavery is officially implemented.

-Make bondage gear do more interesting things (deliberately open-ended!), not just block body zones.  The recent wrist cuff and leg spreader combat tweaks were a great start there.  Also make bondage equipable during sex.  Give some BDSM gear to Vicky, Amber, and Brax to go along with these.

-New fetishes: Rope Bunny and Rigger.  Rope Bunny is the bottom fetish for bondage-related items and actions, which maybe does something when wearing jinxed items. Rigger is the top fetish, and can maybe force bondage items on a foe in combat.

-More SM stuff during sex.  Let sadist NPCs spank the PC while in certain positions (like we can do to them), for starters.  Maybe also minor breast and genital abuse (painful squeezing, biting clit/dick/nipples, etc.).

-Sex scene with Finch.  I'm assuming he's exclusively a top.  He has some specially-enchanted fetish gear for the occasion: it's jinxed, but he can remove it normally, and the collar forces its wearer to obey him but isn't considered legal enslavement.  Finch offers to use it on the PC  Maybe give him a bottom coworker (a personal slave assistant?) that can be involved for top PCs.

-Voluntary enslavement.  If the PC is carrying a collar or anything with the "of Enslavement" modifier, while interacting with an NPC who has high affection for them, and neither is already a slave, you can offer to enslave or be enslaved by them.  Most NPCs with Submissive will never accept owning the PC, and most with Dominant will never accept being owned, though a Switch is open to either.  Also, many story characters will probably refuse for story reasons (though I doubt Amber or Vicky will turn away an eager bitch).

**Comment by Nenoxx** [comment]
Please leave this place to bug reports only, this is not the place to make suggestions.

**Comment by Innoxia** [comment]
Thank you for the suggestions! I've taken note of these and will try to include your ideas when I add more BDSM content. ^^
