### ISSUE TITLE
Entering submission not correctly placing the NPC on the correct entrance

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#501]
**Version** : 0.2.5.5
**From** : Discord
**Date** : 18/05/2018

*"Entering Submission 3 squares south and 4 squares west from Lilaya's mansion deposits you into the upper left-most area of Submission, at least the first time you enter it since updating. Not sure of subsequent visits."*

**Comment by Innoxia** [comment]
This will be fixed in 0.2.5.6. ^^
