### ISSUE TITLE
Imported character causes wrong addiction

### ISSUE THREAD

**Issue by dinodick** [Innoxia/liliths-throne-public#509]
Imported wolf caused human cum addiction instead of lupine

**Comment by ThatWhichLurks** [comment]
Just observed something possibly related.  Made a potion to turn a character into a futa greater demon with addictive fluids.  Force-fed it to a rabbit-girl.  After a couple messy couplings, I got addicted to demonic cum like expected, but the girl-cum addiction came up as rabbit-morph.  (She's not lactating, so no clue if her milk changed species tag properly.)
