### ISSUE TITLE
The buttons to change Jam's Lilaya portraits don't work

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#512]
**Version** : 0.2.5.5
**From** : Blogspot
**Date** : 20 May 2018

![image](https://user-images.githubusercontent.com/23719598/40277878-21a469f4-5c27-11e8-9013-aab809f30549.png)

**Comment by Garnetxx** [comment]
It's because if you changed the portrait to Chattyneko's... it defaults to it every time you want to change back to Jams. This issue is also in 2.6.1
![screen shot 2018-06-03 at 10 18 32 pm](https://user-images.githubusercontent.com/38672011/40899494-1f470756-677c-11e8-91ae-0da6f6a5e232.png)

**Comment by Innoxia** [comment]
Is fixed for 0.2.6.5
