### ISSUE TITLE
Reporting back to Claire after finding a slime shows the dialogue for the finished quest

### ISSUE THREAD

**Issue by Mach565** [Innoxia/liliths-throne-public#522]
After finding a slime in Submission and reporting back to Claire with what you found, it shows the dialogue for when you've finished the quest, though the quest screen itself shows the correct progress.

**Comment by Rfpnj** [comment]
Has been fixed on Innoxias Local copy, am going to link to other PR so both are closed at once

**Comment by Mach565** [comment]
Fix has been merged.
