### ISSUE TITLE
Flying

### ISSUE THREAD

**Issue by abishaij1** [Innoxia/liliths-throne-public#523]
Both in the Harpy Cave and with the new Slime Queen quest flying isn't an option for me as a demon with wings.

**Comment by Nenoxx** [comment]
Edit your title to correctly reflect the problem your encountered, for example "Flying option not available during the Slime Queen quest despite my character having demon wings" 

Something like that

**Comment by A-Master-of-Puppets** [comment]
It isn't enough to just have wings, they must be of at least average size for you to be able to fly. It will tell you on the selfie screen what size your wings are.

**Comment by CognitiveMist** [comment]
Note: Maybe it is worth adjusting the tooltip from "You aren't able to fly" to "Your wings aren't large enough to fly (at all/that far)" to cover this case.
