### ISSUE TITLE
Issue with slavery upkeed and balance being kept over a new game

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#531]
**Version** : 0.2.5.8
**Date** : 24 May 2018

*"When saving a file with a PC who has slaves, and then, without leaving the game, making a new game, you get to pay the upkeep of the previous save. (I just got my slaver license and don't even have any slave room yet)"*

*"Quitting the game and reloading the save seems to fix the upkeep
(But not the balance ._.)"*

**Comment by Pimvgd** [comment]
Caused by place upgrades not being reset when starting a new game
