### ISSUE TITLE
Fox-morphs and related subspecies

### ISSUE THREAD

**Issue by tukaima** [Innoxia/liliths-throne-public#533]
Copying over from the current suggestions list channel.

"Fox-morphs, as well as subspecies related to foxes, including "kitsune" and fennecs."

**Comment by tukaima** [comment]
#383 is in a decent enough state that it could be merged and it would satisfy this suggestion; it includes both kitsune, fennecs, and even a union of both subspecies, a fennec-gitsune.

**Comment by Innoxia** [comment]
Added for 0.2.8. ^^

Thank you so much for the PR @tukaima!
