### ISSUE TITLE
Duplicate rewards in the gambling den, despite losing the game

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#670]
**Version** : 0.2.6
**Date** : 1 June 2018

*"In the Gambling Den when you lose and offer body when you click Accept it doesnt work and continously clicking accept then decline seems to multiple a Reward."*

![:3](https://cdn.discordapp.com/attachments/302618549820850176/452052172595527680/56f9abfd4bf86858b99a5001fb2e844b.png)

**Comment by Pimvgd** [comment]
Seems fixed in 0.2.6.1
