### ISSUE TITLE
ClassCastException when loading 0.1.84 save in 0.1.84.1

### ISSUE THREAD

**Issue by nonchip** [Innoxia/liliths-throne-public#69]
when trying to load a save from 0.1.84 into 0.1.84.1 (both using `[Resume]` and explicit loading) I get:

> `java.lang.ClassCastException`: cannot assign instance of `com.base.game.character.body.types.BodyCoveringType` to field `com.base.game.character.body.Eye.type` of type `com.base.game.character.body.types.EyeType` in instance of `com.base.game.character.body.Eye`

after which the whole UI just hangs (e.g. all buttons stop working, including `[Quit]` etc).

given that previously if you broke save compatibility those old saves didn't show up in stuff like Resume and Load screens I think you might want to know this. (also the version number sounds like it's just supposed to be a small patch, so I don't think this should happen)

**Comment by Pimvgd** [comment]
This will always happen until save compatibility is in. The game uses java's built-in serialization for saving and that doesn't play nice when you add fields or change classes into enums and such.

Suggested to close as won't fix.

**Comment by nonchip** [comment]
well but before it didn't just throw an error to stderr and then freeze the whole UI, but actually prevent me from trying to load it, so I thought this might be just something that was somehow missed and just wanted to report it.

**Comment by Innoxia** [comment]
Thank you for the report (and I'm sorry it's taken me so long to respond), but as Pimgd says, Java's "Serialized" interface doesn't play nice with changes to enums. I've almost got save compatibility working now (using .xml file exports in place of Serialized classes), so this will not be an issue for much longer. ^^
