### ISSUE TITLE
Wrong text display on slime queen report

### ISSUE THREAD

**Issue by Tyrn-11** [Innoxia/liliths-throne-public#694]
SubmissionGenericPlaces.java, On line 530:
return new Response("Report Back", "Report to Claire that you've defeated the Slime Queen.", CLAIRE_INFO_REPORT_BACK) {
should be
return new Response("Report Back", "Report to Claire that you've defeated the Slime Queen.", CLAIRE_INFO_SLIME_QUEEN_REPORT_BACK) {

As it is now, the quest is turned in correctly but Claire just repeats the dame dialogue she used for the original slime report.

**Comment by Pimvgd** [comment]
Thanks, I've turned this into a PR.
