### ISSUE TITLE
Girlcum doesn't change when pussy is transformed

### ISSUE THREAD

**Issue by NinAc-of-the-Southern-Tower** [Innoxia/liliths-throne-public#700]
easiest to verify in a milking room or on characters with addictive girlcum

**Comment by ThatWhichLurks** [comment]
Issue #526, among others, have noticed the same thing.  I did some fairly extensive experimentation, and as far as I can tell, breast and penis racial TFs update species tags for their respective fluids as one would expect, but pussy racial TFs don't, so anyone generated with no vagina only ever produces the default human fluid, and anyone generated with one, that of its original species.
