### ISSUE TITLE
Submissive Sex in Public Stocks Area

### ISSUE THREAD

**Issue by LaTeChien** [Innoxia/liliths-throne-public#702]
Engaging in submissive sex with a party member in the public stocks area traps you in a never-ending loop.
Also, the positioning options disappear one by one as you click on them, leaving only 'swap with'.

**Comment by Pimvgd** [comment]
Do you have a savefile or error.log for this?

**Comment by Innoxia** [comment]
After trying with both dominant and submissive sex, I was unable to replicate this. If, as Pimvgd says, you're able to provide an error log or save file, then please reopen this issue! ^^
