### ISSUE TITLE
Pattern text gets applied to every piece of clothing of alley characters

### ISSUE THREAD

**Issue by Tyrn-11** [Innoxia/liliths-throne-public#707]
Specifically, if a character gets generated with a piece of clothing that has a pattern, all clothing they wear gets generated with the name-addition of the pattern. For example, if a character wears a 'tiger-striped' t-shirt, their shoes and socks etc. will also have 'tiger-striped' added to their names, despite being a single color/having no pattern.

**Comment by Innoxia** [comment]
Fixed. :3
