### ISSUE TITLE
Typo in Nipple to Lipple transformation scene.

### ISSUE THREAD

**Issue by S-abLE** [Innoxia/liliths-throne-public#708]
Build: 0.2.6.2
Your **lipples** suddenly grow sore and sensitive, and before you have any time to react, they suddenly swell up and transform into juicy pairs of lips!
Your rosy nipples, with fleshy-pink internal walls lipples have transformed into lip-like lipples, which you can control just like regular lips!

Correction: "Your **nipples** suddenly..."

**Comment by Innoxia** [comment]
Fixed for the next update. :3
