### ISSUE TITLE
Clothing with patterns not stacking properly

### ISSUE THREAD

**Issue by Innoxia** [Innoxia/liliths-throne-public#712]
"Small bug with the new patterns on clothing. If you already have an item the same type and color, say for instance; dark blue briefs and you add a horizontal tiger stripe dark blue briefs the pattern seems to be lost and it is added as just another item in the stack."

**Comment by Pimvgd** [comment]
To fix; make use of the pattern in Clothing's equals

**Comment by Innoxia** [comment]
Fixed. :3
