### ISSUE TITLE
writing permissions

### ISSUE THREAD

**Issue by Phoenixcan** [Innoxia/liliths-throne-public#714]
Right, so yesterday I saved two separate game files, 1 of me trying to see how far I can get by being a prude soldier woman, and the other is mess around and explore the world. Right because of internet Issues I saved my open game, and restarted my laptop. Eventually when I get back to the game, I see that my game's saves are all gone. I am currently testing what happens and if I can recreate it. 

I'm on windows 10 though not updated to the latest (It's a waste of time, 6mbs makes it take a year)
My save does in fact save, and I can reload those, but when I left the game, they are all gone.
I'm on the .32 exe version
Version 0.2.6.2

I'll try to keep you guys posted

ps. I'm fairly new to downloading games on pc, so I don't know the proper ways to do things, like should I move the games out of winrar files

**Comment by Pimvgd** [comment]
Yes you should move it out of the zipped archive; Windows makes a TEMPORARY directory when you open these! Whilst the directory or files using the directory are opened by other programs, the directory stays open. When you restart your computer, it's possible for Windows to delete the directory! Thus your saves disappear.

**Comment by Phoenixcan** [comment]
Right, well I did that a while ago while looking through the individual sub files, and when I tried opening up the game I got an error

**Comment by Phoenixcan** [comment]
... can someone describe writing permissions and how to give something it

I made a file name folder and I get this when I try to save the game... so I need to know about writing permissions

![err](https://user-images.githubusercontent.com/17116571/40946456-3338ab82-6823-11e8-9363-fbd4a9b3809d.PNG)

**Comment by Innoxia** [comment]
Fixed by running the game in admin mode.
