### ISSUE TITLE
Typo when you reveal your strap-on in sex scene.

### ISSUE THREAD

**Issue by S-abLE** [Innoxia/liliths-throne-public#716]
Version: 0.2.6.2
Dialogue: Your hard dildo is now exposed! Brandy grins as she sees that you're wearing a strap-on. "Looking to a little extra fun, huh?!"
Fix: Whoever wrote this might have meant;
1. "Looking to add a little extra fun, huh?!"
2. "Looking to have a little extra fun, huh?!"
3. "Looking at a little extra fun, huh?!" This one seems unlikely
Additions: I'd think about removing the exclamation mark. I doubt it was made to be a shout, nor is it fitting.

**Comment by Innoxia** [comment]
Changed to "Looking to have a little extra fun, huh?" for 0.2.6.5
