### ISSUE TITLE
Loading an enchantment should override the enchantment that are already on the collar and not be unable to being loaded.

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#719]
**Version** : 0.2.6.2
**Date** : 5 May 2018

I just saved an enchantment file for the cowbell collar and when I try to load it again on the very same collar, well I can't.

**EDIT : It's because of the +5 Physique that is by default on the collar, therefore I think that you should be able to load it and have all the enchantment override the ones that are already on the collar.
I changed the title accordingly.**

![image](https://user-images.githubusercontent.com/23719598/40983098-25117324-68df-11e8-89c6-d515eca8dd60.png)

![image](https://user-images.githubusercontent.com/23719598/40983134-3c7c5862-68df-11e8-8bde-499467d495f1.png)

**Comment by Innoxia** [comment]
Fixed for 0.2.6.5
