### ISSUE TITLE
Error with "generateNPCInteractionEvent"

### ISSUE THREAD

**Issue by AlacoGit** [Innoxia/liliths-throne-public#724]
Got this error while testing for other bugs. 

Error log:
[error.log](https://github.com/Innoxia/liliths-throne-public/files/2073493/error.log)

**Comment by Innoxia** [comment]
Fixed for 0.2.6.5 :3

**Comment by AlacoGit** [comment]
Yeah, but i'm not taking all the blame for this :D. The game currently ships with "DEBUG = true" so its not reporting/resetting the error.log on game start, so I though the issue kept happening. :P
