### ISSUE TITLE
Grammar enhancement 

### ISSUE THREAD

**Issue by AlacoGit** [Innoxia/liliths-throne-public#728]
Reported by anakha3263#0187 on Discord.

"Shouldn't this be '...slam your hips backwards...'? forwards would sound like I've just started planking. She's kneeling behind me, I'm on all fours. I apologise if I sound odd when I'm framing these, Games Dev + English teacher does not make a good combination, 3/10 do not recommend."

https://puu.sh/AzEOF.png

**Comment by Innoxia** [comment]
Fixed for 0.2.6.5
