### ISSUE TITLE
Kneeling position cunnilingus "O" lockout 2.6.5

### ISSUE THREAD

**Issue by HarelMym** [Innoxia/liliths-throne-public#741]
Compiled 2.5.8, playing as Greater Angel Herm with ADDICTIVE, ALCOHOLIC, BUBBLING, HALLUCINOGENIC, MUSKY, SLIMY, STICKY, VISCOUS Girl_Cum (no issues with same char on 2.5.2) and when (NPC) Sub is kneeling in sex giving cunnilingus, at orgasm, the options of Thigh squeeze, and Cum locations don't do anything, and the came can't advance. Other buttons such as menu, phone work, but the scene controls do nothing. Only closing the game or loading a game/new game 'fixes' the issue.

Appears on Mutual Orgasm, so far

**Comment by CognitiveMist** [comment]
This should be fixed by PR #739 which Inno merged yesterday.

**Comment by HarelMym** [comment]
@CognitiveMist Thanks, I'll check that out.

**Comment by HarelMym** [comment]
Yes, that appears to have fixed the issue.
