### ISSUE TITLE
Grow Cock = 1 inch (in version 0.2.6.5, build from 3ebb762 commit)

### ISSUE THREAD

**Issue by Garnetxx** [Innoxia/liliths-throne-public#742]
In 0.2.6.2 it is fine and working.
In 0.2.6.5 (build from 3ebb762 commit (I use git pull and mvn package)):
"Grow Cock" is unclickable upon new game when doing "test" with Liliya (it disappears when browsing other menu)
I try to press it, but can't trigger the dialog for it, and then I shift through Liliya's cloths and she has a 1 inch cock. On existing game she has 18inch, but can't trigger the dailog for "Grow Cock"/the button doesn't click through.

[error.log](https://github.com/Innoxia/liliths-throne-public/files/2083301/error.log)
![growcock](https://user-images.githubusercontent.com/38672011/41144480-e8f5a67e-6ab1-11e8-96fc-3547b6b46309.gif)

**Comment by Nenoxx** [comment]
Couldn't replicate this bug with an old save or a fresh new game, might it be because the game runs under Java 9?

**Comment by Garnetxx** [comment]
Yes, the game was run in Java 9 on mac 10.9.5.
When I updated to Java SDK 10.0.1, apparently JavaFX support starts on mac 10.10.

**Comment by Garnetxx** [comment]
The game runs fine by compiling with Java 8, and plays fine on Java 9 on macOS 10.9.5. Doesn't play fine on the lastest Java 8 / Java 10 on 10.9.5, but an update of my OS will fix this probably.
