### ISSUE TITLE
Dialogue in Slime Queen quest repeats

### ISSUE THREAD

**Issue by Mthrndr01** [Innoxia/liliths-throne-public#744]
When completing the final report of the Slime queen quest the dialogue that shows is for the previous stage in the [quest.] The reward is still 20k, so it seems to just be a text thing.

**Comment by Tyrn-11** [comment]
This should already be fixed with PR #696 
That PR should also be in the latest public release, are you perhaps using an old version?

**Comment by Mthrndr01** [comment]
The version that's up on the blog anyway. Didn't see anything listed here for it so posted in case it had been missed.
