### ISSUE TITLE
When submitting to Epona after trading in six stamps, a name is missing from one of the paragraphs

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#748]
**Version** : 0.2.6.5
**Date** : 9 June 2018

Reporting this issue from Patreon

*"If it's ok with you, could you take charge? you ask, stepping around behind the counter before moving up next to Epona.
INVALID_TARGET_NAME the horse-girl says, placing a 'Be back soon' sign on the counter"*

**Comment by WoefulWombat** [comment]
PR #749 should fix that.

**Comment by Innoxia** [comment]
Fixed by WoefulWombat's PR. :3
