### ISSUE TITLE
Slime transit transformations

### ISSUE THREAD

**Issue by HarelMym** [Innoxia/liliths-throne-public#762]
Is it intentional that a character can't become a 'greater' whatever by transitioning through slime because the hair type is not transformable? If not, please set it so that slimes may select their hair type too; it's an interesting way to select all your traits, and become a greater 'whatever-morph', angel, imp or demon without cheating. Additionally, penis color is not optional as a slime, so when you go back to fleshliness, it's an olive penis.

**Comment by Innoxia** [comment]
Hair type transformation has been added to the slime TF menu for 0.2.7. Thank you for reporting this! ^^

I also added slime penis recolouring for 0.2.7. ^^
