### ISSUE TITLE
Harpy Matriarch dialogue.

### ISSUE THREAD

**Issue by Ringenkoji** [Innoxia/liliths-throne-public#764]
During the Harpy Matriarch quest, when I call them ugly and they order their subordinate to attack me, when referring to me, they say 'you' instead of he/she/her/him.

Brittany: "Lauren! Get you! Get you! Nobody talks to me like that!"
Diane: "Harley! Fuck you up! Beat you into submission! That fucking bitch! Get you!"
Lexi: "Max! Get you! Get you! That fucker! You said I was ugly!"

**Comment by Innoxia** [comment]
Fixed for 0.2.7. Thank you for the report! :3
