### ISSUE TITLE
Bat-morph skin error.

### ISSUE THREAD

**Issue by Ringenkoji** [Innoxia/liliths-throne-public#765]
When changing Bat-morph skin color at Kate's, the color palette has the 'basic' skin colors (Porcelain to Ebony) listed twice.

![bat-error](https://user-images.githubusercontent.com/39977051/41284272-721e6a68-6dfe-11e8-83e0-3bc65d70ab7c.jpg)

**Comment by Innoxia** [comment]
Fixed for the incoming 0.2.7.1 hotfix. Thank you for the report!
