### ISSUE TITLE
Demon tail hair color error.

### ISSUE THREAD

**Issue by Ringenkoji** [Innoxia/liliths-throne-public#767]
When growing a hair tipped demon tail on a character who has never had demonic hair, the tail's hair color is impossible to change (there isn't a section for it), and the color is randomized when loading a save.

Transforming the character's hair into demon hair permanently fixes the color randomization (even if the hair type is changed to another race), but the color can still only be changed so long as the character has demon hair. Transforming the hair to another race makes the tail hair color unchangeable again.

**Comment by Innoxia** [comment]
Fixed for 0.2.7.1 ^^
