### ISSUE TITLE
Parsers are broken

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#769]
**Version** : 0.2.7
**Date** : 14 June 2018

![image](https://user-images.githubusercontent.com/23719598/41402925-d6e6c492-6fc3-11e8-979d-3d6fa4cdf581.png)

**Comment by Nenoxx** [comment]
Ok, it seems the bugs with Lilaya's and Kate's sex scenes are broken due to that as well, here is the error.log I get : 

***Failed to parse: [lilaya.secondPenisColourPrimary(Example argument)]
java.lang.NullPointerException***

***Failed to parse: [lilaya.secondPenisColourHex]
java.lang.NullPointerException***

***Failed to parse: [lilaya.money(Example argument)]
java.lang.ArrayIndexOutOfBoundsException: 1***

Full error.log after trying to have sex with Lilaya : 
[error.log](https://github.com/Innoxia/liliths-throne-public/files/2101651/error.log)

**Comment by Innoxia** [comment]
Fixed for incoming 0.2.7.1 hotfix
