### ISSUE TITLE
Losing your penis and balls does not disable the cum production

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#770]
**Version** : 0.2.7
**Date** : 14 June 2018

*"I lost my cock but I still have the cum production status effect."*
*"I also get the full balls status effect, it seems my capacity goes down on each orgasm and when it fills completely it gives me the -5 malus"*

**Comment by Innoxia** [comment]
Fixed for 0.2.7.1 :3
