### ISSUE TITLE
Interacting with partner clothing during Chair Sex permanently disables third tab.

### ISSUE THREAD

**Issue by Nezumi-chan** [Innoxia/liliths-throne-public#774]
In either of the chair sex scenes, attempting to remove or displace partner clothing, either single items or all at once, causes the third tab to break from then on. In the scene in question, trying to select the third tab results in non-interactive buttons and the screen not updating, though tooltips do;

![2018-06-14 1](https://user-images.githubusercontent.com/18333613/41416910-3647cf64-6fa9-11e8-9e3e-c218d62303f6.png)

Loading an earlier save will fix the issue, but even after quitting and reloading, any save after this point will have this problem.

It also appears to happen when interacting with own clothing, at least sometimes. Not tested that aspect thoroughly.

Error Log:

[error.log](https://github.com/Innoxia/liliths-throne-public/files/2103198/error.log)

**Comment by Nenoxx** [comment]
Add your error.log to the main post, please. It's located in the data folder

**Comment by Innoxia** [comment]
Fixed for incoming 0.2.7.1 hotfix. Thank you for the report! ^^
