### ISSUE TITLE
Bugs and missing content.

### ISSUE THREAD

**Issue by colin18swood** [Innoxia/liliths-throne-public#776]
BUG -- In the change-log (0.2.7) it says:

"Fixed legs and arms always being described as 'slender'. The description is now drawn from your BodyShape (which is based on muscle and body size)."

but in the game I made a jacked female character and it still says:

"All of your limbs are slender and feminine looking."

Also, almost all hair modifiers other than Ombre have vanished.

**Comment by Innoxia** [comment]
Fixed for 0.2.7.5. ^^
