### ISSUE TITLE
Incest Submission Bug

### ISSUE THREAD

**Issue by Phoenixcan** [Innoxia/liliths-throne-public#777]
Bug report: you can't have Submissive sex with a child of yours after combat with them, no matter how corrupted you are, if you are without the Fetish of Submissive
![in sub bug](https://user-images.githubusercontent.com/17116571/41454772-5401a4e8-7040-11e8-9d08-3e03262a257a.PNG)

**Comment by Phoenixcan** [comment]
There are 2 things missing, corruption, and incest

**Comment by IvoryOwl92** [comment]
That's not a bug. If you don't have the Submissive Fetish then you can't submit after winning a battle; buy it first from the Fetish list if you want access to that content. Also corruption is currently just a stat boost, it doesn't affect sex other than giving you corruption points when you do something outside of your "comfort zone".

**Comment by Ringenkoji** [comment]
v0.2.5.1 patch notes
All 'Submit' actions in the game are no longer completely locked out by not having the Submissive fetish, and instead have an associated corruption bypass cost.

It's a bug.

**Comment by IvoryOwl92** [comment]
Welp, how did I missed that? My bad.

**Comment by Innoxia** [comment]
Fixed for 0.2.7.5. :3
