### ISSUE TITLE
Found the reason for Penile Virgin bug

### ISSUE THREAD

**Issue by Phoenixcan** [Innoxia/liliths-throne-public#779]
https://github.com/Innoxia/liliths-throne-public/blob/master/src/com/lilithsthrone/game/sex/Sex.java#L1

		String penileVirginityLoss = ""; 		 		if (penetrationType == SexAreaPenetration.PENIS) { 			if(characterPenetrating.isPenisVirgin() 					&& characterPenetrating.hasPenisIgnoreDildo() 					&& orifice.isTakesPenisVirginity()) { 				penileVirginityLoss = characterPenetrating.getVirginityLossPenetrationDescription(characterPenetrating, SexAreaPenetration.PENIS, characterPenetrated, orifice); 				if(characterPenetrated.hasFetish(Fetish.FETISH_DEFLOWERING)) { 					characterPenetrated.incrementExperience(Fetish.getExperienceGainFromTakingOtherVirginity(characterPenetrated), true); 					characterPenetrated.incrementFetishExperience(Fetish.FETISH_DEFLOWERING, Fetish.FETISH_DEFLOWERING.getExperienceGainFromSexAction()); 				} 				characterPenetrating.setVirginityLoss(relatedSexTypeForCharacterPenetrating, characterPenetrated.getName("a") + " " + characterPenetrated.getLostVirginityDescriptor()); 				characterPenetrating.setPenisVirgin(false);

characterPenetrated.getLostVirginityDescriptor()); 
Is the issue,  you should relook at your code, sorry I don't know how to code so I can't help

**Comment by Pimvgd** [comment]
Possibly the cause is different;
![779](https://user-images.githubusercontent.com/20502925/41509563-58d9ee86-7256-11e8-9e9d-4cf4878fbaed.PNG)

**Comment by Innoxia** [comment]
Fixed for 0.2.7.5. ^^
