### ISSUE TITLE
Clothing incorrectly says 'cum production' when it boosts 'cum storage' 

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#780]
**Version** : 0.2.7
**Date** : 16 June 2018

*"basically clothing wetness is correct, it should just say "storage" rather than "production"
although "wetness" made sense when it was production + storage
not sure whether it shouldn't just be labeled "fluid capacity" now"*

**Comment by Pimvgd** [comment]
See also

Item effects
`case TF_MOD_WETNESS:
                        switch(potency) {
                            case MAJOR_DRAIN:
                                return new RacialEffectUtil("Huge decrease in maximum cum storage.", largeChangeMajorDrain, "ml") { @Override public String applyEffect() { return target.incrementPenisCumStorage(largeChangeMajorDrain); } };
                            case DRAIN:
                                return new RacialEffectUtil("Decrease in maximum cum storage.", largeChangeDrain, "ml") { @Override public String applyEffect() { return target.incrementPenisCumStorage(largeChangeDrain); } };
                            case MINOR_DRAIN:
                                return new RacialEffectUtil("Small decrease in maximum cum storage.", largeChangeMinorDrain, "ml") { @Override public String applyEffect() { return target.incrementPenisCumStorage(largeChangeMinorDrain); } };
                            case MINOR_BOOST: default:
                                return new RacialEffectUtil("Small increase in maximum cum storage.", largeChangeMinorBoost, "ml") { @Override public String applyEffect() { return target.incrementPenisCumStorage(largeChangeMinorBoost); } };
                            case BOOST:
                                return new RacialEffectUtil("Increase in maximum cum storage.", largeChangeBoost, "ml") { @Override public String applyEffect() { return target.incrementPenisCumStorage(largeChangeBoost); } };
                            case MAJOR_BOOST:
                                return new RacialEffectUtil("Huge increase in maximum cum storage.", largeChangeMajorBoost, "ml") { @Override public String applyEffect() { return target.incrementPenisCumStorage(largeChangeMajorBoost); } };
                        }`

Clothing effects:

`case TF_MOD_WETNESS:
                            if(isWithinLimits(cumProductionIncrement, target.getPenisRawCumStorageValue(), limit)) {
                                sb.append(target.incrementPenisCumStorage(cumProductionIncrement));
                            } else if(isSetToLimit(cumProductionIncrement, target.getPenisRawCumStorageValue(), limit)) {
                                sb.append(target.setPenisCumStorage(limit));
                            }
                            break;`

and clothing descriptions

`case TF_MOD_WETNESS:
                        descriptions.add(getClothingTFChangeDescriptionEntry(potency, "cum production", limit+"ml"));
                        break;`

**Comment by Innoxia** [comment]
I've changed the instance of "cum production" to "cum storage", and added a regeneration enchantment to clothing. :3
