### ISSUE TITLE
Lots of stuff vanished in 2.7.1?

### ISSUE THREAD

**Issue by ThatWhichLurks** [Innoxia/liliths-throne-public#781]
A few self-TF options for demons and slimes seem to have gone missing, as another recent issue points out (edit: it's #776). Also, Finch's shop and Nyan's specials are missing a lot of stock: everything but basic collars and novelty tees. (Haven't checked the Gambling Den yet.)

Edit: can no longer choose to enjoy or eagerly receive nipple fingering. Edit 2: ...except from an alley succubus.  Possibly checking for partner penetrable nipples instead of PC?  Edit 3: Saw someone on the blog commenting urethra seems similarly bugged, haven't personally verified.

**Comment by Innoxia** [comment]
Fixed all issues for 0.2.7.5. ^^

**Comment by irregarde** [comment]
Still having the issue with Finch's shop in 2.10.8
