### ISSUE TITLE
Parsing errors talking with Crystal and Blaze

### ISSUE THREAD

**Issue by NinAc-of-the-Southern-Tower** [Innoxia/liliths-throne-public#782]
![taco](https://user-images.githubusercontent.com/39883578/41496074-18316e5a-70fc-11e8-96d8-92bd466bf273.png)

**Comment by Innoxia** [comment]
Fixed after 0.2.7.5's release. Will no longer be an issue for 0.2.8. ^^

Thank you for the report!
