### ISSUE TITLE
Mod clothing errors aren't helpful

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#790]
**Version** : 0.2.7.1
**Date** : 18 June 2018

*"Mod clothing doesn't print exception to error.log when loading fails, it prints a generic unhelpful message
this is a bug because generic unhelpful messages when the game DOESN'T START are evil
additionally, 2nd bug; mod clothing that fails to load should not be loaded into the game anyway"*

**Comment by Pimvgd** [comment]
} catch(Exception ex) {
				//ex.printStackTrace();
				System.err.println("ClothingType was unable to be loaded from file!");
			}

this part of AbstractClothingType needs to be adjusted for printing better error messages;

										AbstractClothingType ct = new AbstractClothingType(innerChild) {};
										moddedClothingList.add(ct);

This part needs adjusting to disregard load failures.

So wrap it in try catch and skip to the next mod to be loaded if it can't be loaded.

**Comment by Innoxia** [comment]
Done, thank you both for the report (Nenoxx) and the fixes (Pimvgd)! :3
