### ISSUE TITLE
No "stroke cock (self)" option appearing in sex

### ISSUE THREAD

**Issue by AbsolutlySolid** [Innoxia/liliths-throne-public#800]
![screenshot 115](https://user-images.githubusercontent.com/40380002/41579071-569e550e-7363-11e8-8188-6dcb5584622e.png)

This was in previous versions, was it removed? I've looked around and didn't see anything saying so. Is this just me getting this problem?

**Comment by Innoxia** [comment]
This will be fixed & restored in 0.2.7.5. ^^
