### ISSUE TITLE
You have taken your penile virginity

### ISSUE THREAD

**Issue by Leonais** [Innoxia/liliths-throne-public#801]
Clothing removal - You unbutton your boxer shorts
Your throbbing cock is now exposed!
The squirrel-boy lets out a derisive sneer as your average-sized dick is revealed, That's pretty big, I guess.​..​

The squirrel-boy looks down at you as you kneel beneath him, This is going to be good!
> Dirty talk
Looking up at the squirrel-boy standing above you, you speak up to him, Let's have some fun!

The squirrel-boy looks down at you as you kneel beneath him, This is going to be good!
> Dirty talk
You glance up at the squirrel-boy as you speak up to him, Let's have some fun!

Looking down at you, the squirrel-boy groans, You're going to be a good boy!
> Dirty talk
Looking up at the squirrel-boy standing above you, you speak up to him, I'll do whatever you want!

Looking down at you, the squirrel-boy groans, Ready for some fun?
> Dirty talk
Looking up at the squirrel-boy standing above you, you speak up to him, Let's have some fun!

The squirrel-boy looks down at you as you kneel beneath him, Ready for some fun?
> Dirty talk
Looking up at the squirrel-boy standing above you, you speak up to him, Let's get started!

Reaching down to grab your head, the squirrel-boy lines the head of his dick up to your lips, before eagerly pushing his hips forwards and sliding his hard shaft into your mouth.​ You let out a deep grunt, sliding your head forwards as you start sucking his throbbing cock.​
The squirrel-boy lets out a low grunt as he pushes his cock into your mouth.​
You have taken your penile virginity!
Your saliva quickly lubricates the squirrel-boy's cock.​

This was a new character, male with sex experience, who deliberately lost the first fight to test transforms. The Squirrel boy turned him into a squirrel trap and this was the sex after. I've no idea if the squirrel was the virgin.

**Comment by Pimvgd** [comment]
See #779

**Comment by Innoxia** [comment]
Fixed for 0.2.7.5. ^^
