### ISSUE TITLE
Parser error in the wing description for demons

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#805]
**Version** : 0.2.7.5
**Date** : 21 June 2018

Basically, the text refers to the player's wings instead of the NPC's wings.. You're missing a "n" there, Inno :3 

==> `[npc.she] has a pair of [npc.wingSize] bat-like wings, which are covered in [pc.wingFullDescription(true)]`

![image](https://user-images.githubusercontent.com/23719598/41715969-44458230-7555-11e8-8257-6b0c516e158c.png)

**Comment by Innoxia** [comment]
Fixed for 0.2.8. ^^
