### ISSUE TITLE
Game soft-locked during sex with a harpy

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#808]
**Version** : 0.2.7.5
**Date** : 21 June 2018

*"Got another one - game locked up during sex with a Harpy. Wasn't paying close attention to what happened to cause it - but shortly before the game soft-locked, I did attempt to change positions and was rebuffed by her. This one produced errors, at least, so here's the error.log:"*

[error.log](https://github.com/Innoxia/liliths-throne-public/files/2123382/error.1.log)

**Comment by Innoxia** [comment]
Fixed for 0.2.8. :3
