### ISSUE TITLE
Fox tails can't penetrate?

### ISSUE THREAD

**Issue by jkk321** [Innoxia/liliths-throne-public#827]
Furry tail penetration is on but no tail related actions are available...

**Comment by IvoryOwl92** [comment]
Not all tails are prehensile enough to be used during sex.

**Comment by TadUnlikely** [comment]
@Innoxia Looks like this one can be closed, not a bug.

**Comment by Innoxia** [comment]
Thank you, yes, this is not a bug. As IvoryOwl says, only prehensile tails can be used in sex.
