### ISSUE TITLE
0.2.7.8 - Actions described as being done to yourself

### ISSUE THREAD

**Issue by LeechingLecher** [Innoxia/liliths-throne-public#840]
Initiating kissing: "You let out a desperate groan as you push your tongue into you's mouth.​"
Creampie in Missionary: "Feeling yourself reaching your climax, you let out a desperate grunt as you lean down on top of you.​ "

Not sure if it occurs elsewhere.

**Comment by Nenoxx** [comment]
They've been reported here and fixed already, you can close this

**Comment by LeechingLecher** [comment]
Oh, didn't catch them because they were too specific. Closing.
