### ISSUE TITLE
Un-/equipping Full Chastity Belt is blocked by sealed Ankles item on Slave

### ISSUE THREAD

**Issue by Zsar** [Innoxia/liliths-throne-public#858]
Version 0.2.8.2 on Java 1.8.0_161

Reproduced with both Chastity Belt and Full Chastity Belt.
Reproduced with vanilla Spreader Bar and Sealed Shin guards.

Steps to reproduce:

**Behaviour on PC** (expected)
1. equip jinxed Ankles item
2. equip unjinxed Full Chastity Belt
3. unequip unjinxed Full Chastity Belt

**Behaviour on Slave** (bugged)
1. equip jinxed Ankles item
2. equip unjinxed Full Chastity Belt
- _Bug: Step fails with message that item from step 1) cannot be removed!_
3. unjinx item from step 1)
4. repeat step 2
5. repeat step 1
6. unequip item from step 4
- _Bug: Step fails with message that item from step 5) cannot be removed!_

Recommended fix: The same code should govern both behaviours. Behaviour on PC is deemed correct. NPC duplicate code should be removed.

**Comment by Zsar** [comment]
Reproduced in 0.3.2.2 Alpha.

PC is now bugged in the same way as the slave.

**Comment by Zsar** [comment]
Issue seems to be that the belts require
```
ClothingAccess.LEGS_UP_TO_GROIN_LOW_LEVEL,
ClothingAccess.LEGS_UP_TO_GROIN,
```
to be equipped.

… Their in-game image seems to suggest that both loops of these belts can be opened - then they would not require those tags.

**Comment by Zsar** [comment]
Went ahead and tried it. Cursory testing does not reveal undue behaviour.
[Pull Request here](https://github.com/Innoxia/liliths-throne-public/pull/1130)

Input on further testing focus desired.

**Comment by Innoxia** [comment]
Fixed
