### ISSUE TITLE
Some sex actions return blank descriptions

### ISSUE THREAD

**Issue by AlacoGit** [Innoxia/liliths-throne-public#860]
Reported by Leob70#7278 on Discord.

" SO im in the gentle pace and have the gently hotdogged action but im not the dominant partner Instead of displaying my actions it gives a blank
It also appears NPCs have some of the same incorrect actions that they can choose resulting in a blank on their end, notice how one of the turns has no text at all"

According to Noivern#4230 on Discord this also happens with nipple penetration.

![leobbug](https://user-images.githubusercontent.com/37576132/42541941-ce4a075e-84a4-11e8-968f-777ffedce292.png)

**Comment by Innoxia** [comment]
Fixed for 0.2.8.5. Thank you again for the report! ^^
