### ISSUE TITLE
Reproduceable Bugs for Version 0.2.10.2 .exe

### ISSUE THREAD

**Issue by TheWeirdling** [Innoxia/liliths-throne-public#901]
The following are 100% reproduce-able for me:

1.

when losing to transforming slime in submission and drinking the slime transformative both the slime transformation text is skipped and no corruption is gained by the character.  This issue has been active for me since forced slime transformations were introduced.

If one submits the slime transformation text is displayed but the character does not gain corruption.   

 (note I had the Test Subject Fetish).

2.
If you and a summoned elemental engage in a threesome with an ally-way attacker and the elemental orgasms then the elemental will immediately end intimacy.  Afterwards the character menu for the elemental locks up and you can no longer dismiss them or access any of their party menu options.   

There is a work around: if you add a slave to your party you can access their character menu and use it to access the elemental's menu and dismiss them.  This bug only seams to occur with elemental party members and not slave NPCs

3.
During threesomes your companion will often be the subject of narrative instead of the allyway attacker.  For instance I had an elemental getting a blowjob by an ally-way attacker and in simplification the text read:  "Elemental moans as elemental sucks elemental's cock description cock"

This bug also happens for slave companions.

4.
Any time the player inserts their penis into an orifice, the first penis descriptor is from the players perspective, e.g. "your tentacles wiggle as your cock goes down X's throat." But the SECOND penis descriptor you have, such as prehensile, will be incorrectly narrated as if the orifice has that modifier.  For instance, if you have a penis that also had prehensile then the orifice will be narrated as having intricate internal muscles.  This does not change any additional dialog or options.

5.
All dialog for dirty/rough talk does not play when the character is engaged in oral or anal sex penetrative sex.  Instead of lines like "what a horny buttslut you are"  both characters will say "yeah",  "fuck" and similar none specific dialog.    Note I have had an item equipped that gives me the bimbo fetish; if removing it fixes the bug I will update this section.

Update: added more bugs, minor spell checking

**Comment by RiyuG** [comment]
I've got one. When I click on threesomes with my arcane elemental, the game will then lock out the sex menu. Happened twice now.
