### ISSUE TITLE
Defeat transformation issues (Test subject fetish + human genitals)

### ISSUE THREAD

**Issue by vmattwin** [Innoxia/liliths-throne-public#92]
To make your work easier:
Forced TF w/ the TF Subject Fetish is broken due to a change that got pulled (accidentally?) with the alligator morph merge:
In `game.character.npc.NPC`, generateTransformativePotion, the final lines were mixed up. 

`ItemEffect effect = keysAsArray.get(Util.random.nextInt(keysAsArray.size()));`

was commented out, and 

`possibleEffects.get(effect),`

was changed. Reverting them causes the fetish to work properly.

The human-only tf results are due to the same function using default values for everything. They are initalized at the start (

`AbstractItemType genitalsItemType = ItemType.RACE_INGREDIENT_HUMAN;`

) but are never altered, and thus all the effects returned are human-based. Previously, they were altered in each of the switch statements. It looks like some consolidation (using itemtype for genitalitemtype) was intended, but not completed. 

I went and converted them, then compiled, and it worked properly.

**Comment by Innoxia** [comment]
Thank you! I missed this for the hotfix, but I'll correct it now and push the updated version to github. :3

**Comment by Innoxia** [comment]
This should now be fixed. :3
