### ISSUE TITLE
getPlayerPenisRevealReaction size comparisons from masculine NPCs

### ISSUE THREAD

**Issue by tukaima** [Innoxia/liliths-throne-public#95]
getPlayerPenisRevealReaction has several responses from masculine NPCs that reference their own dick size without checking whether the character in question has a dick, and also doesn't actually compare their own penis size to that of the player.

The following cases result in masculine NPCs comparing the player's cock size to their own (including masculine NPCs who do not have cocks.) In all cases except the third, the NPC assumes that their cock is smaller than that of the player.

- Feminine player's cock size is >FOUR_HUGE, <=SIX_GIGANTIC, player is domming
- Feminine player's cock size is >FOUR_HUGE, <=SIX_GIGANTIC, player is subbing
- Masculine player's cock size is <=ONE_TINY, player is subbing
- Masculine player's cock size is >TWO_AVERAGE, <=FOUR_HUGE, player is domming
- Masculine player's cock size is >TWO_AVERAGE, <=FOUR_HUGE, player is subbing
- Masculine player's cock size is >FOUR_HUGE, <=SIX_GIGANTIC, player is domming
- Masculine player's cock size is >FOUR_HUGE, <=SIX_GIGANTIC, player is subbing

**Comment by Innoxia** [comment]
Fixed for upcoming version 0.1.97.5. Thank you for the report! ^^
