### ISSUE TITLE
0.2.11.9 - Clothing no longer replaced after sex

### ISSUE THREAD

**Issue by LeechingLecher** [Innoxia/liliths-throne-public#963]
Clothing that were shifted aside during sex is no longer replaced after sex is stopped. This is the case for both the player and slaves. Have not tested unequipping during sex.

I don't think this issue was present in the previous build.

**Comment by NinAc-of-the-Southern-Tower** [comment]
It's not just the player and slaves, as far as I can tell it applies to every character.  I tested it on a few different NPCs and they're still baring themselves to the world.

Unequiped and dropped clothing still gets replaces afterward.
