### ISSUE TITLE
Test subject transformations are labeled as "masculine" and "feminine" even for futanarization

### ISSUE THREAD

**Issue by Pimvgd** [Innoxia/liliths-throne-public#972]
Which leads to things like

![unknown](https://user-images.githubusercontent.com/20502925/48985067-39ff5c80-f104-11e8-8cdc-6ab8f2460666.png)
![unknown](https://user-images.githubusercontent.com/20502925/48985073-48e60f00-f104-11e8-8e63-dee997b8a1bf.png)

**Comment by Pimvgd** [comment]
It seems to me that the easiest fix would be to add a new SlaveEventTag for this case. See also 
https://github.com/Innoxia/liliths-throne-public/blob/a770eacac7102fe6402632c89e11d08e904bab35/src/com/lilithsthrone/game/occupantManagement/SlaveEventTag.java#L94

and 

https://github.com/Innoxia/liliths-throne-public/blob/152d6a00ce47f6e29cd1292b68a78e26403f0d15/src/com/lilithsthrone/game/occupantManagement/OccupancyUtil.java#L608

**Comment by Innoxia** [comment]
Fixed, thank you for the report!
