### ISSUE TITLE
Damage tooltips show different values before and after buying a weapon from a shop

### ISSUE THREAD

**Issue by Pimvgd** [Innoxia/liliths-throne-public#975]
Before buying:

![unknown](https://user-images.githubusercontent.com/20502925/49046094-43a3c580-f1d3-11e8-9244-c6c8880ae689.png)

After buying:

![unknown](https://user-images.githubusercontent.com/20502925/49046109-528a7800-f1d3-11e8-9b32-c87af9cbfda2.png)

**Comment by bicobus** [comment]
The difference is simply your modifiers being applied to the base item.

**Comment by Innoxia** [comment]
Fixed for 0.3. Thank you for the report!
