### ISSUE TITLE
Importing pregnant NPCs adds incorrect/nonexistent IDs to Finch's list of slaves

### ISSUE THREAD

**Issue by tukaima** [Innoxia/liliths-throne-public#99]
Impregnate an NPC and then export them. Import them into a new game, and purchase them from the auction. If you view Finch's profile then, his profile will either list the slave you just purchased as his own property, or it will list him as his own slave. I first viewed Finch's profile from within the Slavery Administration just after purchasing a slave, and it listed the slave's name. When I went to Lilaya's house and viewed Finch's profile on the phone, it listed his own name as well.

**Comment by Innoxia** [comment]
Fixed for upcoming version 0.1.97.5. Thank you for the report!
