### ISSUE TITLE
Crash when entering buildings

### ISSUE THREAD

**Issue by Willned** [Innoxia/liliths-throne-public#990]
When I try to enter any building (e.g. shopping arcade, harpy nest), the game stops. 
Only the home seams to work. I tested it with my current save, a new save and a fresh copy of the game

Version: 0.12.9
[error.log](https://github.com/Innoxia/liliths-throne-public/files/2669750/error.log)

**Comment by IvoryOwl92** [comment]
It was fixed in 0.12.95. Your version is outdated.
Try to avoid reporting bugs from older versions because chances are those problems have already been fixed. In the future, get the latest release and see if the problem persists, then make a report.

**Comment by Willned** [comment]
I am really sorry. I had the blog open in another tab and thought that it was a freshly loaded version. Therefore I thought 0.12.9 was still the current version (simply because I did not see the new one). I also did not see another report of this, when I quickly looked at the most recent ones.

I am sorry, I will make sure to reload every page twice before reporting anything again.
