### ISSUE TITLE
Locked in Bondage set bugs buttons

### ISSUE THREAD

**Issue by RandomNecromancer** [Innoxia/liliths-throne-public#991]
When a Npc is wearing the Locked in Bondage set (slaves and non-slaves), almost all sex-related buttons disappear or stop working during sex

i'm not an english speaker, please forgive any error

**Comment by IvoryOwl92** [comment]
What version are you playing?

**Comment by DrZed** [comment]
It could've been unintentionally fixed, or such a minor bug they fixed when passing by the code, take this from a developer himself, we do more than what we list, we just can't be bothered to list everything when they're tiny bugs, simple issues, etc..

**Comment by DrZed** [comment]
After a cursory search through the code, I'd say it was possibly fixed in this commit...
https://github.com/Innoxia/liliths-throne-public/commit/afb7c13dc2f3b90617a20ff0ddc4264381839e04

**Comment by RandomNecromancer** [comment]
it seems that innoxia must have forgot to add this to one to the bug fixing session of the posts, since i've seen bugs even minor than mine's there. anyway, sorry for the bother.

**Comment by DrZed** [comment]
> it seems that innoxia must have forgot to add this to one to the bug fixing session of the posts, since i've seen bugs even minor than mine's there. anyway, sorry for the bother.

I don't mean the bug being minor in frustration, I mean minor in scope, as in how much it affects, or how hard it was to fix, it could've been as simple as a number being off by 1, such a small bug would've been forgotten in a standard coding session (4+ hours).
